<?php

return [
    'default' => [
        'key' => 'default',
        'name' => 'Default Theme',
        'path' => base_path('frontend/theme-default/templates'),
        'assets_url' => '/frontend/theme-default/assets',
        'engine' => 'twig',
        'twig_ready' => true,
        'templates_path' => base_path('frontend/theme-default/templates'),
        'description' => 'Thème de référence compact, Bootstrap-compatible, SEO-first.',
        'appearance_defaults' => [
            'body_font_family' => 'system',
            'heading_font_family' => 'system',
            'main_heading_font_family' => 'heading',
            'main_heading_letter_spacing' => 'normal',
            'show_site_title_in_header' => true,
            'color_background' => '#fbfcfe',
            'color_surface' => '#ffffff',
            'color_text' => '#102033',
            'color_muted' => '#627086',
            'color_primary' => '#1b5fc1',
            'color_accent' => '#ffb21e',
        ],
    ],
    'aurora' => [
        'key' => 'aurora',
        'name' => 'Aurora Fullscreen',
        'path' => base_path('frontend/theme-aurora/templates'),
        'assets_url' => '/frontend/theme-aurora/assets',
        'engine' => 'twig',
        'twig_ready' => true,
        'templates_path' => base_path('frontend/theme-aurora/templates'),
        'description' => 'Template éditorial élégant avec hero plein écran, superposition de contenu et palette sobre mais chaleureuse.',
        'appearance_defaults' => [
            'body_font_family' => 'system',
            'heading_font_family' => 'serif',
            'main_heading_font_family' => 'arial',
            'main_heading_letter_spacing' => 'normal',
            'show_site_title_in_header' => true,
            'color_background' => '#fbf7ef',
            'color_surface' => '#fffaf2',
            'color_text' => '#162026',
            'color_muted' => '#66747d',
            'color_primary' => '#13242b',
            'color_accent' => '#ef8f4e',
        ],
    ],

    'pulse' => [
        'key' => 'pulse',
        'name' => 'Pulse',
        'path' => base_path('frontend/theme-pulse/templates'),
        'assets_url' => '/frontend/theme-pulse/assets',
        'engine' => 'twig',
        'twig_ready' => true,
        'templates_path' => base_path('frontend/theme-pulse/templates'),
        'description' => 'Template outdoor moderne, coloré et énergique pour sites sportifs, touristiques et expérientiels.',
        'appearance_defaults' => [
            'body_font_family' => 'system',
            'heading_font_family' => 'system',
            'main_heading_font_family' => 'arial',
            'main_heading_letter_spacing' => 'normal',
            'show_site_title_in_header' => true,
            'color_background' => '#f6fbff',
            'color_surface' => '#ffffff',
            'color_text' => '#102033',
            'color_muted' => '#5d6f86',
            'color_primary' => '#2667ff',
            'color_accent' => '#ff6b4a',
        ],
    ],
];
