-- Seed de contrat multisite/multilingue deterministe.
PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;
DELETE FROM public_content_snapshots WHERE site_id IN (10,11);
DELETE FROM search_documents WHERE site_id IN (10,11);
DELETE FROM seo_metadata WHERE site_id IN (10,11);
DELETE FROM routes WHERE site_id IN (10,11);
DELETE FROM content_slug_registry WHERE site_id IN (10,11);
DELETE FROM content_entry_taxonomy_terms WHERE entry_id BETWEEN 1000 AND 1199;
DELETE FROM content_entry_publications WHERE entry_id BETWEEN 1000 AND 1199;
DELETE FROM content_entry_working_revisions WHERE entry_id BETWEEN 1000 AND 1199;
DELETE FROM menu_item_localizations WHERE menu_item_id BETWEEN 10000 AND 11999;
DELETE FROM menu_items WHERE menu_id IN (1010,1011,1110,1111);
DELETE FROM menus WHERE site_id IN (10,11);
DELETE FROM taxonomy_term_localizations WHERE site_id IN (10,11);
DELETE FROM taxonomy_terms WHERE taxonomy_id IN (1010,1110);
DELETE FROM content_type_taxonomies WHERE taxonomy_id IN (1010,1110);
DELETE FROM taxonomies WHERE site_id IN (10,11);
DELETE FROM media_asset_localizations WHERE media_id IN (1010,1110);
DELETE FROM media_assets WHERE site_id IN (10,11);
DELETE FROM media_variant_presets WHERE site_id IN (10,11);
DELETE FROM media_folders WHERE site_id IN (10,11);
DELETE FROM content_entry_localizations WHERE entry_id BETWEEN 1000 AND 1199;
DELETE FROM revisions WHERE resource_type='content_entry' AND resource_id BETWEEN 1000 AND 1199;
DELETE FROM content_entries WHERE site_id IN (10,11);
DELETE FROM site_settings WHERE site_id IN (10,11);
DELETE FROM site_localizations WHERE site_id IN (10,11);
DELETE FROM site_languages WHERE site_id IN (10,11);
DELETE FROM site_domains WHERE site_id IN (10,11);
DELETE FROM sites WHERE site_key IN ('site_a','site_b');
INSERT INTO sites(id, site_key, name, default_language_code, is_active, created_at, updated_at) VALUES(10,'site_a','Site A - Multisite contract','fr',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO sites(id, site_key, name, default_language_code, is_active, created_at, updated_at) VALUES(11,'site_b','Site B - Multisite contract','fr',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_domains(id, site_id, host, base_path, scheme, is_primary, is_active, enforce_https, canonical_host_strategy, created_at, updated_at) VALUES(10,10,'multi-a.example.test','/site-a','https',0,1,1,'primary','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_domains(id, site_id, host, base_path, scheme, is_primary, is_active, enforce_https, canonical_host_strategy, created_at, updated_at) VALUES(11,11,'multi-b.example.test','/site-b','https',0,1,1,'primary','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_domains(id, site_id, host, base_path, scheme, is_primary, is_active, enforce_https, canonical_host_strategy, created_at, updated_at) VALUES(1012,10,'webe.li','/cms/site-a','https',1,1,1,'primary','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_domains(id, site_id, host, base_path, scheme, is_primary, is_active, enforce_https, canonical_host_strategy, created_at, updated_at) VALUES(1112,11,'webe.li','/cms/site-b','https',1,1,1,'primary','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_languages(id, site_id, language_code, locale, url_prefix, hreflang_code, fallback_language_code, is_default, is_active, is_rtl, sort_order, created_at, updated_at) VALUES(100,10,'fr','fr-CH','','fr-CH',NULL,1,1,0,1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_languages(id, site_id, language_code, locale, url_prefix, hreflang_code, fallback_language_code, is_default, is_active, is_rtl, sort_order, created_at, updated_at) VALUES(101,10,'en','en-GB','/en','en-GB','fr',0,1,0,2,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_languages(id, site_id, language_code, locale, url_prefix, hreflang_code, fallback_language_code, is_default, is_active, is_rtl, sort_order, created_at, updated_at) VALUES(110,11,'fr','fr-CH','','fr-CH',NULL,1,1,0,1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_languages(id, site_id, language_code, locale, url_prefix, hreflang_code, fallback_language_code, is_default, is_active, is_rtl, sort_order, created_at, updated_at) VALUES(111,11,'en','en-GB','/en','en-GB','fr',0,0,0,2,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_languages(id, site_id, language_code, locale, url_prefix, hreflang_code, fallback_language_code, is_default, is_active, is_rtl, sort_order, created_at, updated_at) VALUES(112,11,'de','de-CH','/de','de-CH','fr',0,1,0,3,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO media_folders(id, site_id, folder_key, name, parent_id, sort_order, created_at, updated_at) VALUES(1010,10,'site-a','Médias Site A',NULL,10,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO media_folders(id, site_id, folder_key, name, parent_id, sort_order, created_at, updated_at) VALUES(1110,11,'site-b','Médias Site B',NULL,10,'2026-05-16 12:00:00','2026-05-16 12:00:00');
-- Presets responsives natifs par sous-site. Sans ces lignes, les uploads Site A/B
-- n'ont pas la même politique de variants que le site central.
INSERT INTO media_variant_presets(site_id, preset_key, width, height, format, quality, mode, sort_order, is_active)
SELECT s.id, v.preset_key, v.width, v.height, v.format, v.quality, v.mode, v.sort_order, 1
FROM sites s
JOIN (
    SELECT 'content_480' AS preset_key, 480 AS width, NULL AS height, 'webp' AS format, 82 AS quality, 'fit' AS mode, 10 AS sort_order UNION ALL
    SELECT 'content_768', 768, NULL, 'webp', 82, 'fit', 20 UNION ALL
    SELECT 'content_1024', 1024, NULL, 'webp', 82, 'fit', 30 UNION ALL
    SELECT 'content_1280', 1280, NULL, 'webp', 82, 'fit', 40 UNION ALL
    SELECT 'content_1600', 1600, NULL, 'webp', 82, 'fit', 50 UNION ALL
    SELECT 'hero_640', 640, NULL, 'webp', 82, 'fit', 110 UNION ALL
    SELECT 'hero_960', 960, NULL, 'webp', 82, 'fit', 120 UNION ALL
    SELECT 'hero_1280', 1280, NULL, 'webp', 82, 'fit', 130 UNION ALL
    SELECT 'hero_1920', 1920, NULL, 'webp', 82, 'fit', 140 UNION ALL
    SELECT 'og_1200x630', 1200, 630, 'webp', 82, 'crop', 210
) v
WHERE s.site_key IN ('site_a','site_b')
ON CONFLICT(site_id, preset_key) DO UPDATE SET
    width=excluded.width,
    height=excluded.height,
    format=excluded.format,
    quality=excluded.quality,
    mode=excluded.mode,
    sort_order=excluded.sort_order,
    is_active=1,
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO media_assets(id, uuid, site_id, storage_disk, path, public_path, filename, original_filename, extension, mime_type, media_type, size_bytes, width, height, sha256, lifecycle_status, validation_status, variants_status, metadata_status, folder_id, created_at, updated_at) VALUES(1010,'00000000-0000-4000-8000-000000001010',10,'local','site-a/hero-a.webp','site-a/hero-a.webp','hero-a.webp','hero-a.webp','webp','image/webp','image',1234,1200,630,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','ready','valid','ready','complete',1010,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO media_assets(id, uuid, site_id, storage_disk, path, public_path, filename, original_filename, extension, mime_type, media_type, size_bytes, width, height, sha256, lifecycle_status, validation_status, variants_status, metadata_status, folder_id, created_at, updated_at) VALUES(1110,'00000000-0000-4000-8000-000000001110',11,'local','site-b/hero-b.webp','site-b/hero-b.webp','hero-b.webp','hero-b.webp','webp','image/webp','image',1234,1200,630,'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','ready','valid','ready','complete',1110,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO media_asset_localizations(media_id, language_code, alt_text, caption, title, is_alt_verified, updated_at) VALUES(1010,'fr','Visuel propre au site A','Média isolé du site A','Hero Site A',1,'2026-05-16 12:00:00');
INSERT INTO media_asset_localizations(media_id, language_code, alt_text, caption, title, is_alt_verified, updated_at) VALUES(1110,'fr','Visuel propre au site B','Média isolé du site B','Hero Site B',1,'2026-05-16 12:00:00');
INSERT INTO site_localizations(id, site_id, language_code, site_title, baseline, footer_text, default_meta_title_suffix, default_meta_description, og_default_image_media_id, apple_touch_icon_media_id) VALUES(100,10,'fr','Site A','Site A isolé','Footer Site A depuis la base','· Site A','Description SEO du site A multisite.',1010,NULL);
INSERT INTO site_localizations(id, site_id, language_code, site_title, baseline, footer_text, default_meta_title_suffix, default_meta_description, og_default_image_media_id, apple_touch_icon_media_id) VALUES(101,10,'en','Site A','Isolated Site A','Site A footer from database','· Site A','SEO description for Site A.',1010,NULL);
INSERT INTO site_localizations(id, site_id, language_code, site_title, baseline, footer_text, default_meta_title_suffix, default_meta_description, og_default_image_media_id, apple_touch_icon_media_id) VALUES(110,11,'fr','Site B','Site B isolé','Footer Site B depuis la base','· Site B','Description SEO du site B multisite.',1110,NULL);
INSERT INTO site_localizations(id, site_id, language_code, site_title, baseline, footer_text, default_meta_title_suffix, default_meta_description, og_default_image_media_id, apple_touch_icon_media_id) VALUES(112,11,'de','Site B','Isolierte Site B','Footer Site B aus der Datenbank','· Site B','SEO-Beschreibung für Site B.',1110,NULL);
INSERT INTO media_usages(media_id, site_id, resource_type, resource_id, field_key, language_code, usage_context, source_revision_id, alt_policy, alt_text_snapshot, usage_hash, created_at, updated_at) VALUES(1010,10,'system',0,'localization.og_default_image_media_id','fr','opengraph',NULL,'required','Visuel propre au site A','seed|10|1010|system|0|localization.og_default_image_media_id|fr|opengraph','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO media_usages(media_id, site_id, resource_type, resource_id, field_key, language_code, usage_context, source_revision_id, alt_policy, alt_text_snapshot, usage_hash, created_at, updated_at) VALUES(1010,10,'system',0,'localization.og_default_image_media_id','en','opengraph',NULL,'required',NULL,'seed|10|1010|system|0|localization.og_default_image_media_id|en|opengraph','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO media_usages(media_id, site_id, resource_type, resource_id, field_key, language_code, usage_context, source_revision_id, alt_policy, alt_text_snapshot, usage_hash, created_at, updated_at) VALUES(1110,11,'system',0,'localization.og_default_image_media_id','fr','opengraph',NULL,'required','Visuel propre au site B','seed|11|1110|system|0|localization.og_default_image_media_id|fr|opengraph','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO media_usages(media_id, site_id, resource_type, resource_id, field_key, language_code, usage_context, source_revision_id, alt_policy, alt_text_snapshot, usage_hash, created_at, updated_at) VALUES(1110,11,'system',0,'localization.og_default_image_media_id','de','opengraph',NULL,'required',NULL,'seed|11|1110|system|0|localization.og_default_image_media_id|de|opengraph','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_settings(site_id, namespace, setting_key, value_json, is_public, created_at, updated_at) VALUES(10,'seo','defaults','{"robots":"index,follow","sitemap_enabled":true,"canonical_enabled":true,"redirect_to_primary_host":true,"force_https":true}',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_settings(site_id, namespace, setting_key, value_json, is_public, created_at, updated_at) VALUES(11,'seo','defaults','{"robots":"index,follow","sitemap_enabled":true,"canonical_enabled":true,"redirect_to_primary_host":true,"force_https":true}',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_settings(site_id, namespace, setting_key, value_json, is_public, created_at, updated_at) VALUES(10,'media','defaults','{"max_upload_mb":12,"allowed_mime_types":["image/jpeg","image/png","image/webp","image/gif","video/mp4","video/webm","audio/mpeg","audio/mp4","audio/ogg","application/pdf"],"auto_generate_variants":true,"variant_sets":{"content":[480,768,1024,1280,1600],"hero":[640,960,1280,1920],"open_graph":["1200x630"]},"require_alt_text":true,"default_folder_key":"site-a","logo_media_id":null,"favicon_media_id":null,"default_social_image_media_id":1010,"social_image_policy":{"required_width":1200,"required_height":630,"variant_key":"og_1200x630"}}',0,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO site_settings(site_id, namespace, setting_key, value_json, is_public, created_at, updated_at) VALUES(11,'media','defaults','{"max_upload_mb":12,"allowed_mime_types":["image/jpeg","image/png","image/webp","image/gif","video/mp4","video/webm","audio/mpeg","audio/mp4","audio/ogg","application/pdf"],"auto_generate_variants":true,"variant_sets":{"content":[480,768,1024,1280,1600],"hero":[640,960,1280,1920],"open_graph":["1200x630"]},"require_alt_text":true,"default_folder_key":"site-b","logo_media_id":null,"favicon_media_id":null,"default_social_image_media_id":1110,"social_image_policy":{"required_width":1200,"required_height":630,"variant_key":"og_1200x630"}}',0,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO taxonomies(id, site_id, taxonomy_key, name, description, is_hierarchical, is_localized, seo_enabled, archive_enabled, sort_order) VALUES(1010,10,'topic','Thématiques Site A','Taxonomie propre au site A',1,1,1,1,10);
INSERT INTO taxonomies(id, site_id, taxonomy_key, name, description, is_hierarchical, is_localized, seo_enabled, archive_enabled, sort_order) VALUES(1110,11,'topic','Thématiques Site B','Taxonomie propre au site B',1,1,1,1,10);
INSERT INTO taxonomy_terms(id, taxonomy_id, parent_id, term_key, is_active, sort_order) VALUES(10101,1010,NULL,'actualites',1,10);
INSERT INTO taxonomy_terms(id, taxonomy_id, parent_id, term_key, is_active, sort_order) VALUES(11101,1110,NULL,'actualites',1,10);
INSERT INTO taxonomy_term_localizations(id, site_id, taxonomy_id, term_id, language_code, name, slug, full_path, description, meta_title, meta_description) VALUES(10101,10,1010,10101,'fr','Actualités Site A','actualites','/actualites','Terme isolé du site A','Actualités Site A','Archive Site A');
INSERT INTO taxonomy_term_localizations(id, site_id, taxonomy_id, term_id, language_code, name, slug, full_path, description, meta_title, meta_description) VALUES(10102,10,1010,10101,'en','Site A News','news','/news','Site A isolated term','Site A News','Site A archive');
INSERT INTO taxonomy_term_localizations(id, site_id, taxonomy_id, term_id, language_code, name, slug, full_path, description, meta_title, meta_description) VALUES(11101,11,1110,11101,'fr','Actualités Site B','actualites','/actualites','Terme isolé du site B','Actualités Site B','Archive Site B');
INSERT INTO taxonomy_term_localizations(id, site_id, taxonomy_id, term_id, language_code, name, slug, full_path, description, meta_title, meta_description) VALUES(11102,11,1110,11101,'de','Nachrichten Site B','nachrichten','/nachrichten','Isolierter Begriff Site B','Nachrichten Site B','Site-B-Archiv');
INSERT INTO content_type_taxonomies(content_type_id, taxonomy_id, is_required, max_terms) VALUES(1,1010,0,NULL);
INSERT INTO content_type_taxonomies(content_type_id, taxonomy_id, is_required, max_terms) VALUES(2,1010,0,NULL);
INSERT INTO content_type_taxonomies(content_type_id, taxonomy_id, is_required, max_terms) VALUES(1,1110,0,NULL);
INSERT INTO content_type_taxonomies(content_type_id, taxonomy_id, is_required, max_terms) VALUES(2,1110,0,NULL);
INSERT INTO content_entries(id, site_id, content_type_id, entry_key, author_iam_user_id, owner_iam_user_id, created_by_iam_user_id, updated_by_iam_user_id, published_by_iam_user_id, status, workflow_state, is_active, sort_order, created_at, updated_at, published_at) VALUES(1001,10,1,'site_a_home',1,1,1,1,1,'published','published',1,0,'2026-05-16 12:00:00','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_localizations(entry_id, language_code, title, draft_slug, draft_full_path, translation_status, localized_at, updated_by_iam_user_id, draft_status, is_active, admin_cache_published_at, updated_at) VALUES(1001,'fr','Accueil Site A','accueil','/','reviewed','2026-05-16 12:00:00',1,'ready',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO revisions(id, resource_type, resource_id, revision_number, language_code, workflow_status, document_schema_version, created_from_event, revision_label, summary, change_notes, document_json, checksum_sha256, created_by_iam_user_id, updated_by_iam_user_id, published_by_iam_user_id, created_at, updated_at, published_at) VALUES(1001,'content_entry',1001,1,'fr','published',1,'multisite_contract_seed','Contrat multisite','Page accueil propre au site A.','Seed multisite contract','{"language_code":"fr","content":{"title":"Accueil Site A","slug":"accueil","summary":"Page accueil propre au site A.","blocks":[{"id":"hero","type":"hero","title":"Accueil Site A","text":"Page accueil propre au site A.","enabled":true,"editorial_status":"published","data":{"title":"Accueil Site A","lead":"Page accueil propre au site A."},"sort_order":0}]},"fields":{},"seo":{"meta_title":"Accueil Site A","meta_description":"Page accueil propre au site A.","meta_robots":"index,follow"},"blocks":[{"id":"hero","type":"hero","title":"Accueil Site A","text":"Page accueil propre au site A.","enabled":true,"editorial_status":"published","data":{"title":"Accueil Site A","lead":"Page accueil propre au site A."},"sort_order":0}]}','12500a82cc7ded73e0e06bfcfefb575c294bd4b4952d5ea7be36aa1eaa0425be',1,1,1,'2026-05-16 12:00:00','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_working_revisions(site_id, entry_id, language_code, working_revision_id, workflow_status, updated_by_iam_user_id, created_at, updated_at) VALUES(10,1001,'fr',1001,'published',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_publications(site_id, entry_id, language_code, published_revision_id, workflow_status, published_by_iam_user_id, published_at, updated_at) VALUES(10,1001,'fr',1001,'published',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_slug_registry(site_id, language_code, slug, entry_id, updated_at) VALUES(10,'fr','accueil',1001,'2026-05-16 12:00:00');
INSERT INTO routes(site_id, language_code, resource_type, resource_id, route_type, slug, full_path, is_primary, is_canonical, status, source_published_revision_id, source_revision_checksum_sha256, created_at, updated_at) VALUES(10,'fr','content_entry',1001,'content','accueil','/',1,1,'active',1001,'12500a82cc7ded73e0e06bfcfefb575c294bd4b4952d5ea7be36aa1eaa0425be','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO seo_metadata(site_id, resource_type, resource_id, language_code, meta_title, meta_description, meta_robots, canonical_url, og_title, og_description, og_image_media_id, twitter_title, twitter_description, twitter_image_media_id, hreflang_code, json_ld, seo_score, source_published_revision_id, source_revision_checksum_sha256, updated_at) VALUES(10,'content_entry',1001,'fr','Accueil Site A','Page accueil propre au site A.','index,follow','https://webe.li/cms/site-a/','Accueil Site A','Page accueil propre au site A.',1010,'Accueil Site A','Page accueil propre au site A.',1010,'fr-CH','{"@context":"https://schema.org","@type":"WebPage","name":"Accueil Site A","url":"https://webe.li/cms/site-a/"}',95,1001,'12500a82cc7ded73e0e06bfcfefb575c294bd4b4952d5ea7be36aa1eaa0425be','2026-05-16 12:00:00');
INSERT INTO search_documents(site_id, resource_type, resource_id, language_code, path, title, summary, search_text, source_published_revision_id, source_revision_checksum_sha256, updated_at) VALUES(10,'content_entry',1001,'fr','/','Accueil Site A','Page accueil propre au site A.','Accueil Site A Page accueil propre au site A.',1001,'12500a82cc7ded73e0e06bfcfefb575c294bd4b4952d5ea7be36aa1eaa0425be','2026-05-16 12:00:00');
INSERT INTO public_content_snapshots(site_id, language_code, resource_type, resource_id, route_path, title, slug, blocks_json, block_count, document_json, seo_json, source_published_revision_id, source_revision_checksum_sha256, published_at, projected_at) VALUES(10,'fr','content_entry',1001,'/','Accueil Site A','accueil','[{"id":"hero","type":"hero","title":"Accueil Site A","text":"Page accueil propre au site A.","enabled":true,"editorial_status":"published","data":{"title":"Accueil Site A","lead":"Page accueil propre au site A."},"sort_order":0}]',1,'{"language_code":"fr","content":{"title":"Accueil Site A","slug":"accueil","summary":"Page accueil propre au site A.","blocks":[{"id":"hero","type":"hero","title":"Accueil Site A","text":"Page accueil propre au site A.","enabled":true,"editorial_status":"published","data":{"title":"Accueil Site A","lead":"Page accueil propre au site A."},"sort_order":0}]},"fields":{},"seo":{"meta_title":"Accueil Site A","meta_description":"Page accueil propre au site A.","meta_robots":"index,follow"},"blocks":[{"id":"hero","type":"hero","title":"Accueil Site A","text":"Page accueil propre au site A.","enabled":true,"editorial_status":"published","data":{"title":"Accueil Site A","lead":"Page accueil propre au site A."},"sort_order":0}]}','{"meta_title":"Accueil Site A","meta_description":"Page accueil propre au site A.","meta_robots":"index,follow"}',1001,'12500a82cc7ded73e0e06bfcfefb575c294bd4b4952d5ea7be36aa1eaa0425be','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entries(id, site_id, content_type_id, entry_key, author_iam_user_id, owner_iam_user_id, created_by_iam_user_id, updated_by_iam_user_id, published_by_iam_user_id, status, workflow_state, is_active, sort_order, created_at, updated_at, published_at) VALUES(1002,10,1,'site_a_shared',1,1,1,1,1,'published','published',1,0,'2026-05-16 12:00:00','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_localizations(entry_id, language_code, title, draft_slug, draft_full_path, translation_status, localized_at, updated_by_iam_user_id, draft_status, is_active, admin_cache_published_at, updated_at) VALUES(1002,'fr','Slug partagé Site A','shared-slug','/shared-slug','reviewed','2026-05-16 12:00:00',1,'ready',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO revisions(id, resource_type, resource_id, revision_number, language_code, workflow_status, document_schema_version, created_from_event, revision_label, summary, change_notes, document_json, checksum_sha256, created_by_iam_user_id, updated_by_iam_user_id, published_by_iam_user_id, created_at, updated_at, published_at) VALUES(1002,'content_entry',1002,1,'fr','published',1,'multisite_contract_seed','Contrat multisite','Contenu Site A utilisant un slug identique au site B.','Seed multisite contract','{"language_code":"fr","content":{"title":"Slug partagé Site A","slug":"shared-slug","summary":"Contenu Site A utilisant un slug identique au site B.","blocks":[{"id":"hero","type":"hero","title":"Slug partagé Site A","text":"Contenu Site A utilisant un slug identique au site B.","enabled":true,"editorial_status":"published","data":{"title":"Slug partagé Site A","lead":"Contenu Site A utilisant un slug identique au site B."},"sort_order":0}]},"fields":{},"seo":{"meta_title":"Slug partagé Site A","meta_description":"Contenu Site A utilisant un slug identique au site B.","meta_robots":"index,follow"},"blocks":[{"id":"hero","type":"hero","title":"Slug partagé Site A","text":"Contenu Site A utilisant un slug identique au site B.","enabled":true,"editorial_status":"published","data":{"title":"Slug partagé Site A","lead":"Contenu Site A utilisant un slug identique au site B."},"sort_order":0}]}','3c7ee65a8f17e7d8cdf029b1362b4fa80a4a5412212ae56ebd1e46d4aa3503b6',1,1,1,'2026-05-16 12:00:00','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_working_revisions(site_id, entry_id, language_code, working_revision_id, workflow_status, updated_by_iam_user_id, created_at, updated_at) VALUES(10,1002,'fr',1002,'published',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_publications(site_id, entry_id, language_code, published_revision_id, workflow_status, published_by_iam_user_id, published_at, updated_at) VALUES(10,1002,'fr',1002,'published',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_slug_registry(site_id, language_code, slug, entry_id, updated_at) VALUES(10,'fr','shared-slug',1002,'2026-05-16 12:00:00');
INSERT INTO routes(site_id, language_code, resource_type, resource_id, route_type, slug, full_path, is_primary, is_canonical, status, source_published_revision_id, source_revision_checksum_sha256, created_at, updated_at) VALUES(10,'fr','content_entry',1002,'content','shared-slug','/shared-slug',1,1,'active',1002,'3c7ee65a8f17e7d8cdf029b1362b4fa80a4a5412212ae56ebd1e46d4aa3503b6','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO seo_metadata(site_id, resource_type, resource_id, language_code, meta_title, meta_description, meta_robots, canonical_url, og_title, og_description, og_image_media_id, twitter_title, twitter_description, twitter_image_media_id, hreflang_code, json_ld, seo_score, source_published_revision_id, source_revision_checksum_sha256, updated_at) VALUES(10,'content_entry',1002,'fr','Slug partagé Site A','Contenu Site A utilisant un slug identique au site B.','index,follow','https://webe.li/cms/site-a/shared-slug','Slug partagé Site A','Contenu Site A utilisant un slug identique au site B.',1010,'Slug partagé Site A','Contenu Site A utilisant un slug identique au site B.',1010,'fr-CH','{"@context":"https://schema.org","@type":"WebPage","name":"Slug partag\u00e9 Site A","url":"https://webe.li/cms/site-a/shared-slug"}',95,1002,'3c7ee65a8f17e7d8cdf029b1362b4fa80a4a5412212ae56ebd1e46d4aa3503b6','2026-05-16 12:00:00');
INSERT INTO search_documents(site_id, resource_type, resource_id, language_code, path, title, summary, search_text, source_published_revision_id, source_revision_checksum_sha256, updated_at) VALUES(10,'content_entry',1002,'fr','/shared-slug','Slug partagé Site A','Contenu Site A utilisant un slug identique au site B.','Slug partagé Site A Contenu Site A utilisant un slug identique au site B.',1002,'3c7ee65a8f17e7d8cdf029b1362b4fa80a4a5412212ae56ebd1e46d4aa3503b6','2026-05-16 12:00:00');
INSERT INTO public_content_snapshots(site_id, language_code, resource_type, resource_id, route_path, title, slug, blocks_json, block_count, document_json, seo_json, source_published_revision_id, source_revision_checksum_sha256, published_at, projected_at) VALUES(10,'fr','content_entry',1002,'/shared-slug','Slug partagé Site A','shared-slug','[{"id":"hero","type":"hero","title":"Slug partagé Site A","text":"Contenu Site A utilisant un slug identique au site B.","enabled":true,"editorial_status":"published","data":{"title":"Slug partagé Site A","lead":"Contenu Site A utilisant un slug identique au site B."},"sort_order":0}]',1,'{"language_code":"fr","content":{"title":"Slug partagé Site A","slug":"shared-slug","summary":"Contenu Site A utilisant un slug identique au site B.","blocks":[{"id":"hero","type":"hero","title":"Slug partagé Site A","text":"Contenu Site A utilisant un slug identique au site B.","enabled":true,"editorial_status":"published","data":{"title":"Slug partagé Site A","lead":"Contenu Site A utilisant un slug identique au site B."},"sort_order":0}]},"fields":{},"seo":{"meta_title":"Slug partagé Site A","meta_description":"Contenu Site A utilisant un slug identique au site B.","meta_robots":"index,follow"},"blocks":[{"id":"hero","type":"hero","title":"Slug partagé Site A","text":"Contenu Site A utilisant un slug identique au site B.","enabled":true,"editorial_status":"published","data":{"title":"Slug partagé Site A","lead":"Contenu Site A utilisant un slug identique au site B."},"sort_order":0}]}','{"meta_title":"Slug partagé Site A","meta_description":"Contenu Site A utilisant un slug identique au site B.","meta_robots":"index,follow"}',1002,'3c7ee65a8f17e7d8cdf029b1362b4fa80a4a5412212ae56ebd1e46d4aa3503b6','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entries(id, site_id, content_type_id, entry_key, author_iam_user_id, owner_iam_user_id, created_by_iam_user_id, updated_by_iam_user_id, published_by_iam_user_id, status, workflow_state, is_active, sort_order, created_at, updated_at, published_at) VALUES(1101,11,1,'site_b_home',1,1,1,1,1,'published','published',1,0,'2026-05-16 12:00:00','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_localizations(entry_id, language_code, title, draft_slug, draft_full_path, translation_status, localized_at, updated_by_iam_user_id, draft_status, is_active, admin_cache_published_at, updated_at) VALUES(1101,'fr','Accueil Site B','accueil','/','reviewed','2026-05-16 12:00:00',1,'ready',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO revisions(id, resource_type, resource_id, revision_number, language_code, workflow_status, document_schema_version, created_from_event, revision_label, summary, change_notes, document_json, checksum_sha256, created_by_iam_user_id, updated_by_iam_user_id, published_by_iam_user_id, created_at, updated_at, published_at) VALUES(1101,'content_entry',1101,1,'fr','published',1,'multisite_contract_seed','Contrat multisite','Page accueil propre au site B.','Seed multisite contract','{"language_code":"fr","content":{"title":"Accueil Site B","slug":"accueil","summary":"Page accueil propre au site B.","blocks":[{"id":"hero","type":"hero","title":"Accueil Site B","text":"Page accueil propre au site B.","enabled":true,"editorial_status":"published","data":{"title":"Accueil Site B","lead":"Page accueil propre au site B."},"sort_order":0}]},"fields":{},"seo":{"meta_title":"Accueil Site B","meta_description":"Page accueil propre au site B.","meta_robots":"index,follow"},"blocks":[{"id":"hero","type":"hero","title":"Accueil Site B","text":"Page accueil propre au site B.","enabled":true,"editorial_status":"published","data":{"title":"Accueil Site B","lead":"Page accueil propre au site B."},"sort_order":0}]}','4f83e976d72e7c439882b9fac9752b2d733dc3359f71298af396577877926a94',1,1,1,'2026-05-16 12:00:00','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_working_revisions(site_id, entry_id, language_code, working_revision_id, workflow_status, updated_by_iam_user_id, created_at, updated_at) VALUES(11,1101,'fr',1101,'published',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_publications(site_id, entry_id, language_code, published_revision_id, workflow_status, published_by_iam_user_id, published_at, updated_at) VALUES(11,1101,'fr',1101,'published',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_slug_registry(site_id, language_code, slug, entry_id, updated_at) VALUES(11,'fr','accueil',1101,'2026-05-16 12:00:00');
INSERT INTO routes(site_id, language_code, resource_type, resource_id, route_type, slug, full_path, is_primary, is_canonical, status, source_published_revision_id, source_revision_checksum_sha256, created_at, updated_at) VALUES(11,'fr','content_entry',1101,'content','accueil','/',1,1,'active',1101,'4f83e976d72e7c439882b9fac9752b2d733dc3359f71298af396577877926a94','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO seo_metadata(site_id, resource_type, resource_id, language_code, meta_title, meta_description, meta_robots, canonical_url, og_title, og_description, og_image_media_id, twitter_title, twitter_description, twitter_image_media_id, hreflang_code, json_ld, seo_score, source_published_revision_id, source_revision_checksum_sha256, updated_at) VALUES(11,'content_entry',1101,'fr','Accueil Site B','Page accueil propre au site B.','index,follow','https://webe.li/cms/site-b/','Accueil Site B','Page accueil propre au site B.',1110,'Accueil Site B','Page accueil propre au site B.',1110,'fr-CH','{"@context":"https://schema.org","@type":"WebPage","name":"Accueil Site B","url":"https://webe.li/cms/site-b/"}',95,1101,'4f83e976d72e7c439882b9fac9752b2d733dc3359f71298af396577877926a94','2026-05-16 12:00:00');
INSERT INTO search_documents(site_id, resource_type, resource_id, language_code, path, title, summary, search_text, source_published_revision_id, source_revision_checksum_sha256, updated_at) VALUES(11,'content_entry',1101,'fr','/','Accueil Site B','Page accueil propre au site B.','Accueil Site B Page accueil propre au site B.',1101,'4f83e976d72e7c439882b9fac9752b2d733dc3359f71298af396577877926a94','2026-05-16 12:00:00');
INSERT INTO public_content_snapshots(site_id, language_code, resource_type, resource_id, route_path, title, slug, blocks_json, block_count, document_json, seo_json, source_published_revision_id, source_revision_checksum_sha256, published_at, projected_at) VALUES(11,'fr','content_entry',1101,'/','Accueil Site B','accueil','[{"id":"hero","type":"hero","title":"Accueil Site B","text":"Page accueil propre au site B.","enabled":true,"editorial_status":"published","data":{"title":"Accueil Site B","lead":"Page accueil propre au site B."},"sort_order":0}]',1,'{"language_code":"fr","content":{"title":"Accueil Site B","slug":"accueil","summary":"Page accueil propre au site B.","blocks":[{"id":"hero","type":"hero","title":"Accueil Site B","text":"Page accueil propre au site B.","enabled":true,"editorial_status":"published","data":{"title":"Accueil Site B","lead":"Page accueil propre au site B."},"sort_order":0}]},"fields":{},"seo":{"meta_title":"Accueil Site B","meta_description":"Page accueil propre au site B.","meta_robots":"index,follow"},"blocks":[{"id":"hero","type":"hero","title":"Accueil Site B","text":"Page accueil propre au site B.","enabled":true,"editorial_status":"published","data":{"title":"Accueil Site B","lead":"Page accueil propre au site B."},"sort_order":0}]}','{"meta_title":"Accueil Site B","meta_description":"Page accueil propre au site B.","meta_robots":"index,follow"}',1101,'4f83e976d72e7c439882b9fac9752b2d733dc3359f71298af396577877926a94','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entries(id, site_id, content_type_id, entry_key, author_iam_user_id, owner_iam_user_id, created_by_iam_user_id, updated_by_iam_user_id, published_by_iam_user_id, status, workflow_state, is_active, sort_order, created_at, updated_at, published_at) VALUES(1102,11,1,'site_b_shared',1,1,1,1,1,'published','published',1,0,'2026-05-16 12:00:00','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_localizations(entry_id, language_code, title, draft_slug, draft_full_path, translation_status, localized_at, updated_by_iam_user_id, draft_status, is_active, admin_cache_published_at, updated_at) VALUES(1102,'fr','Slug partagé Site B','shared-slug','/shared-slug','reviewed','2026-05-16 12:00:00',1,'ready',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO revisions(id, resource_type, resource_id, revision_number, language_code, workflow_status, document_schema_version, created_from_event, revision_label, summary, change_notes, document_json, checksum_sha256, created_by_iam_user_id, updated_by_iam_user_id, published_by_iam_user_id, created_at, updated_at, published_at) VALUES(1102,'content_entry',1102,1,'fr','published',1,'multisite_contract_seed','Contrat multisite','Contenu Site B utilisant un slug identique au site A.','Seed multisite contract','{"language_code":"fr","content":{"title":"Slug partagé Site B","slug":"shared-slug","summary":"Contenu Site B utilisant un slug identique au site A.","blocks":[{"id":"hero","type":"hero","title":"Slug partagé Site B","text":"Contenu Site B utilisant un slug identique au site A.","enabled":true,"editorial_status":"published","data":{"title":"Slug partagé Site B","lead":"Contenu Site B utilisant un slug identique au site A."},"sort_order":0}]},"fields":{},"seo":{"meta_title":"Slug partagé Site B","meta_description":"Contenu Site B utilisant un slug identique au site A.","meta_robots":"index,follow"},"blocks":[{"id":"hero","type":"hero","title":"Slug partagé Site B","text":"Contenu Site B utilisant un slug identique au site A.","enabled":true,"editorial_status":"published","data":{"title":"Slug partagé Site B","lead":"Contenu Site B utilisant un slug identique au site A."},"sort_order":0}]}','1340e966742a620d7b4e44a16fd9eda1b3f87ff92042bce034d70145ad962717',1,1,1,'2026-05-16 12:00:00','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_working_revisions(site_id, entry_id, language_code, working_revision_id, workflow_status, updated_by_iam_user_id, created_at, updated_at) VALUES(11,1102,'fr',1102,'published',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_publications(site_id, entry_id, language_code, published_revision_id, workflow_status, published_by_iam_user_id, published_at, updated_at) VALUES(11,1102,'fr',1102,'published',1,'2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_slug_registry(site_id, language_code, slug, entry_id, updated_at) VALUES(11,'fr','shared-slug',1102,'2026-05-16 12:00:00');
INSERT INTO routes(site_id, language_code, resource_type, resource_id, route_type, slug, full_path, is_primary, is_canonical, status, source_published_revision_id, source_revision_checksum_sha256, created_at, updated_at) VALUES(11,'fr','content_entry',1102,'content','shared-slug','/shared-slug',1,1,'active',1102,'1340e966742a620d7b4e44a16fd9eda1b3f87ff92042bce034d70145ad962717','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO seo_metadata(site_id, resource_type, resource_id, language_code, meta_title, meta_description, meta_robots, canonical_url, og_title, og_description, og_image_media_id, twitter_title, twitter_description, twitter_image_media_id, hreflang_code, json_ld, seo_score, source_published_revision_id, source_revision_checksum_sha256, updated_at) VALUES(11,'content_entry',1102,'fr','Slug partagé Site B','Contenu Site B utilisant un slug identique au site A.','index,follow','https://webe.li/cms/site-b/shared-slug','Slug partagé Site B','Contenu Site B utilisant un slug identique au site A.',1110,'Slug partagé Site B','Contenu Site B utilisant un slug identique au site A.',1110,'fr-CH','{"@context":"https://schema.org","@type":"WebPage","name":"Slug partag\u00e9 Site B","url":"https://webe.li/cms/site-b/shared-slug"}',95,1102,'1340e966742a620d7b4e44a16fd9eda1b3f87ff92042bce034d70145ad962717','2026-05-16 12:00:00');
INSERT INTO search_documents(site_id, resource_type, resource_id, language_code, path, title, summary, search_text, source_published_revision_id, source_revision_checksum_sha256, updated_at) VALUES(11,'content_entry',1102,'fr','/shared-slug','Slug partagé Site B','Contenu Site B utilisant un slug identique au site A.','Slug partagé Site B Contenu Site B utilisant un slug identique au site A.',1102,'1340e966742a620d7b4e44a16fd9eda1b3f87ff92042bce034d70145ad962717','2026-05-16 12:00:00');
INSERT INTO public_content_snapshots(site_id, language_code, resource_type, resource_id, route_path, title, slug, blocks_json, block_count, document_json, seo_json, source_published_revision_id, source_revision_checksum_sha256, published_at, projected_at) VALUES(11,'fr','content_entry',1102,'/shared-slug','Slug partagé Site B','shared-slug','[{"id":"hero","type":"hero","title":"Slug partagé Site B","text":"Contenu Site B utilisant un slug identique au site A.","enabled":true,"editorial_status":"published","data":{"title":"Slug partagé Site B","lead":"Contenu Site B utilisant un slug identique au site A."},"sort_order":0}]',1,'{"language_code":"fr","content":{"title":"Slug partagé Site B","slug":"shared-slug","summary":"Contenu Site B utilisant un slug identique au site A.","blocks":[{"id":"hero","type":"hero","title":"Slug partagé Site B","text":"Contenu Site B utilisant un slug identique au site A.","enabled":true,"editorial_status":"published","data":{"title":"Slug partagé Site B","lead":"Contenu Site B utilisant un slug identique au site A."},"sort_order":0}]},"fields":{},"seo":{"meta_title":"Slug partagé Site B","meta_description":"Contenu Site B utilisant un slug identique au site A.","meta_robots":"index,follow"},"blocks":[{"id":"hero","type":"hero","title":"Slug partagé Site B","text":"Contenu Site B utilisant un slug identique au site A.","enabled":true,"editorial_status":"published","data":{"title":"Slug partagé Site B","lead":"Contenu Site B utilisant un slug identique au site A."},"sort_order":0}]}','{"meta_title":"Slug partagé Site B","meta_description":"Contenu Site B utilisant un slug identique au site A.","meta_robots":"index,follow"}',1102,'1340e966742a620d7b4e44a16fd9eda1b3f87ff92042bce034d70145ad962717','2026-05-16 12:00:00','2026-05-16 12:00:00');
INSERT INTO content_entry_taxonomy_terms(entry_id, term_id, sort_order) VALUES(1002,10101,10);
INSERT INTO content_entry_taxonomy_terms(entry_id, term_id, sort_order) VALUES(1102,11101,10);
INSERT INTO menus(id, site_id, menu_key, name, menu_location, language_mode, is_active) VALUES(1010,10,'main','Menu principal Site A','primary','shared',1);
INSERT INTO menus(id, site_id, menu_key, name, menu_location, language_mode, is_active) VALUES(1011,10,'footer','Footer Site A','footer','shared',1);
INSERT INTO menus(id, site_id, menu_key, name, menu_location, language_mode, is_active) VALUES(1110,11,'main','Menu principal Site B','primary','shared',1);
INSERT INTO menus(id, site_id, menu_key, name, menu_location, language_mode, is_active) VALUES(1111,11,'footer','Footer Site B','footer','shared',1);
INSERT INTO menu_items(id, menu_id, language_code, parent_id, resource_type, resource_id, term_id, manual_url, sort_order, is_active) VALUES(10100,1010,NULL,NULL,'content_entry',1001,NULL,NULL,10,1);
INSERT INTO menu_items(id, menu_id, language_code, parent_id, resource_type, resource_id, term_id, manual_url, sort_order, is_active) VALUES(10101,1010,NULL,10100,'content_entry',1002,NULL,NULL,20,1);
INSERT INTO menu_items(id, menu_id, language_code, parent_id, resource_type, resource_id, term_id, manual_url, sort_order, is_active) VALUES(10102,1010,NULL,10100,'taxonomy_term',10101,NULL,NULL,30,1);
INSERT INTO menu_items(id, menu_id, language_code, parent_id, resource_type, resource_id, term_id, manual_url, sort_order, is_active) VALUES(10110,1011,NULL,NULL,'content_entry',1002,NULL,NULL,10,1);
INSERT INTO menu_items(id, menu_id, language_code, parent_id, resource_type, resource_id, term_id, manual_url, sort_order, is_active) VALUES(11100,1110,NULL,NULL,'content_entry',1101,NULL,NULL,10,1);
INSERT INTO menu_items(id, menu_id, language_code, parent_id, resource_type, resource_id, term_id, manual_url, sort_order, is_active) VALUES(11101,1110,NULL,11100,'content_entry',1102,NULL,NULL,20,1);
INSERT INTO menu_items(id, menu_id, language_code, parent_id, resource_type, resource_id, term_id, manual_url, sort_order, is_active) VALUES(11102,1110,NULL,11100,'taxonomy_term',11101,NULL,NULL,30,1);
INSERT INTO menu_items(id, menu_id, language_code, parent_id, resource_type, resource_id, term_id, manual_url, sort_order, is_active) VALUES(11110,1111,NULL,NULL,'content_entry',1102,NULL,NULL,10,1);
INSERT INTO menu_item_localizations(menu_item_id, language_code, label, title_attr) VALUES(10100,'fr','Accueil A','Accueil A');
INSERT INTO menu_item_localizations(menu_item_id, language_code, label, title_attr) VALUES(10101,'fr','Slug partagé A','Slug partagé A');
INSERT INTO menu_item_localizations(menu_item_id, language_code, label, title_attr) VALUES(10102,'fr','Actualités A','Actualités A');
INSERT INTO menu_item_localizations(menu_item_id, language_code, label, title_attr) VALUES(10110,'fr','Footer A','Footer A');
INSERT INTO menu_item_localizations(menu_item_id, language_code, label, title_attr) VALUES(11100,'fr','Accueil B','Accueil B');
INSERT INTO menu_item_localizations(menu_item_id, language_code, label, title_attr) VALUES(11101,'fr','Slug partagé B','Slug partagé B');
INSERT INTO menu_item_localizations(menu_item_id, language_code, label, title_attr) VALUES(11102,'fr','Actualités B','Actualités B');
INSERT INTO menu_item_localizations(menu_item_id, language_code, label, title_attr) VALUES(11110,'fr','Footer B','Footer B');
COMMIT;

DELETE FROM site_settings WHERE namespace = 'api' AND setting_key = 'cors_allowed_origins' AND site_id IN (10,11);
INSERT INTO site_settings(site_id, namespace, setting_key, value_json, is_public, created_at, updated_at) VALUES(10,'api','cors_allowed_origins','["https://front-a.example.test"]',0,'2026-05-31 00:00:00','2026-05-31 00:00:00');
INSERT INTO site_settings(site_id, namespace, setting_key, value_json, is_public, created_at, updated_at) VALUES(11,'api','cors_allowed_origins','["https://front-b.example.test"]',0,'2026-05-31 00:00:00','2026-05-31 00:00:00');
