<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { adminApi, apiErrorMessage } from '@/api/client';

type Row=Record<string,any>;
const props=withDefaults(defineProps<{relationType?:string;relationId?:number}>(),{relationType:'',relationId:0});
const cases=ref<Row[]>([]);const loading=ref(false);const error=ref('');const notice=ref('');const status=ref('pending');
const merge=ref({source_iam_user_id:0,target_iam_user_id:0,reason:'Doublon vérifié par l’opérateur'});const preview=ref<Row|null>(null);const choices=ref<Record<string,string>>({});const separateId=ref(0);
const visible=computed(()=>cases.value.filter(row=>status.value==='all'||row.status===status.value));
async function load(){loading.value=true;error.value='';try{const response=await adminApi.get<{cases:Row[]}>('/sale/customer-identities/review',{limit:100,relation_type:props.relationType||undefined,relation_id:props.relationId||undefined});cases.value=response.data.cases||[]}catch(e){error.value=apiErrorMessage(e)}finally{loading.value=false}}
async function decide(row:Row,action:string){const reason=window.prompt(action==='link'?'Pourquoi ces profils représentent-ils la même personne ?':action==='do_not_link'?'Pourquoi faut-il conserver deux profils distincts ?':'Pourquoi reporter cette décision ?');if(!reason)return;loading.value=true;try{await adminApi.post(`/sale/customer-identities/${row.id}/decision`,{action,reason});notice.value=action==='link'?'Profil lié sans modifier la commande.':action==='do_not_link'?'Profils conservés séparément.':'Décision reportée.';await load()}catch(e){error.value=apiErrorMessage(e)}finally{loading.value=false}}
async function previewMerge(){error.value='';try{const response=await adminApi.post<{preview:Row}>('/sale/customer-accounts/merge-preview',{source_iam_user_id:merge.value.source_iam_user_id,target_iam_user_id:merge.value.target_iam_user_id});preview.value=response.data.preview;choices.value={};for(const field of preview.value.conflicts||[])choices.value[field]=preview.value.fields[field].allowed_choices[0]}catch(e){error.value=apiErrorMessage(e)}}
async function applyMerge(){if(!preview.value||!merge.value.reason.trim())return;loading.value=true;try{await adminApi.post('/sale/customer-accounts/merge',{...merge.value,field_decisions:choices.value});notice.value='Fusion auditée terminée. Les snapshots des commandes sont inchangés.';preview.value=null;await load()}catch(e){error.value=apiErrorMessage(e)}finally{loading.value=false}}
async function separate(){const reason=window.prompt('Motif obligatoire de la séparation');if(!reason||separateId.value<1)return;loading.value=true;try{await adminApi.post(`/sale/customer-accounts/merges/${separateId.value}/separate`,{reason});notice.value='Séparation auditée terminée.';await load()}catch(e){error.value=apiErrorMessage(e)}finally{loading.value=false}}
function value(row:unknown){return row===null||row===undefined||row===''?'—':String(row)}
onMounted(load);
</script>

<template>
 <section class="identity-review">
  <header><div><p>Opérations · Relation 360</p><h2>Rapprochement de profils</h2><span>Relier prudemment les commandes, comptes et fiches Relation sans réécrire l’historique.</span></div><button class="btn btn-outline-primary" :disabled="loading" @click="load">Actualiser</button></header>
  <div v-if="notice" class="alert alert-success">{{ notice }}</div><div v-if="error" class="alert alert-danger" role="alert">{{ error }}</div><p v-if="loading" class="alert alert-info">Analyse en cours…</p>
  <nav class="filters"><button v-for="item in ['pending','postponed','linked','not_linked','all']" :key="item" :class="{active:status===item}" @click="status=item">{{ {pending:'À revoir',postponed:'Reportés',linked:'Liés',not_linked:'Séparés',all:'Tous'}[item] }}</button></nav>
  <p v-if="!loading&&!visible.length" class="empty">Aucun profil à revoir dans cette file.</p>
  <article v-for="row in visible" :key="row.id" class="case">
   <header><div><strong>Commande {{ row.order_number }}</strong><small>Profil transactionnel #{{ row.order_id }}</small></div><div class="confidence" :class="row.confidence_level"><b>{{ row.confidence_score }} %</b><small>Confiance {{ row.confidence_level }}</small></div></header>
   <div class="profiles"><section v-for="(profile,key) in row.profiles" :key="key"><h3>{{ key==='transactional_customer'?'Profil de commande':key==='iam_account'?'Compte client':key==='crm_contact'?'Fiche relation client':'Organisation' }}</h3><p v-if="!profile">Aucun candidat</p><dl v-else><template v-for="(fieldValue,field) in profile.fields" :key="field"><dt>{{ field }}</dt><dd>{{ value(fieldValue) }} <small>{{ row.provenance?.[field]?.map((p:Row)=>p.source).join(', ') }}</small></dd></template></dl></section></div>
   <div class="comparison"><section><h3>Concordances expliquées</h3><p v-for="signal in row.signals" :key="signal.rule">+{{ signal.weight }} · {{ signal.explanation }}</p></section><section><h3>Divergences</h3><p v-if="!row.divergences.length">Aucune divergence détectée.</p><p v-for="item in row.divergences" :key="item.field"><b>{{ item.field }}</b> · {{ item.explanation }}</p></section></div>
   <details><summary>Commandes et activités concernées</summary><p v-for="order in row.orders" :key="order.id">{{ order.order_number }} · {{ order.grand_total_minor/100 }} {{ order.currency }}</p><p v-for="activity in row.activities" :key="activity.id">{{ activity.summary }} · {{ activity.status }}</p></details>
   <footer v-if="['pending','postponed'].includes(row.status)"><button class="btn btn-primary" :disabled="!row.candidate_iam_user_id&&!row.candidate_crm_contact_id" @click="decide(row,'link')">Lier</button><button class="btn btn-outline-danger" @click="decide(row,'do_not_link')">Ne pas lier</button><button class="btn btn-outline-secondary" @click="decide(row,'postpone')">Reporter</button></footer>
  </article>
  <section class="merge"><h2>Fusion contrôlée</h2><p>L’aperçu exige une décision pour chaque valeur en conflit. L’e-mail vérifié cible reste protégé.</p><div class="merge-form"><label>Compte source<input v-model.number="merge.source_iam_user_id" type="number" min="1"></label><label>Compte cible<input v-model.number="merge.target_iam_user_id" type="number" min="1"></label><label>Motif<input v-model="merge.reason"></label><button class="btn btn-outline-primary" @click="previewMerge">Prévisualiser</button></div><div v-if="preview" class="preview"><p><b>{{ preview.orders_affected }}</b> commande(s) concernée(s) · snapshots immuables</p><label v-for="field in preview.conflicts" :key="field">{{ field }}<span>Source : {{ value(preview.fields[field].source) }} · Cible : {{ value(preview.fields[field].target) }}</span><select v-model="choices[field]"><option v-for="choice in preview.fields[field].allowed_choices" :key="choice" :value="choice">{{ choice==='source'?'Conserver la source':'Conserver la cible' }}</option></select></label><button class="btn btn-danger" @click="applyMerge">Fusionner avec ces décisions</button></div><div class="separate"><label>Journal de fusion à séparer<input v-model.number="separateId" type="number" min="1"></label><button class="btn btn-outline-danger" @click="separate">Séparer</button></div></section>
 </section>
</template>

<style scoped>
.identity-review{display:grid;gap:1rem}.identity-review>header,.case>header,.case footer{display:flex;justify-content:space-between;gap:1rem}.identity-review>header p{margin:0;color:#6366f1;font-size:.75rem;font-weight:700;text-transform:uppercase}.filters{display:flex;gap:.4rem;flex-wrap:wrap}.filters button{border:1px solid #cbd5e1;background:#fff;border-radius:999px;padding:.4rem .8rem}.filters .active{background:#312e81;color:#fff}.case,.merge{border:1px solid #e2e8f0;background:#fff;border-radius:.8rem;padding:1rem;display:grid;gap:1rem}.confidence{display:grid;text-align:right}.confidence.high{color:#15803d}.confidence.medium{color:#b45309}.confidence.low{color:#b91c1c}.profiles{display:grid;grid-template-columns:repeat(4,1fr);gap:.7rem}.profiles section,.comparison section{background:#f8fafc;border-radius:.6rem;padding:.8rem;min-width:0}.profiles h3,.comparison h3{font-size:.9rem}.profiles dl{display:grid;grid-template-columns:auto 1fr;gap:.25rem}.profiles dt{font-weight:700}.profiles dd{overflow-wrap:anywhere}.profiles small{display:block;color:#64748b}.comparison{display:grid;grid-template-columns:1fr 1fr;gap:.7rem}.case footer{justify-content:flex-end}.merge-form{display:grid;grid-template-columns:1fr 1fr 2fr auto;gap:.7rem;align-items:end}.merge label,.preview label,.separate label{display:grid;gap:.25rem}.merge input,.merge select{border:1px solid #cbd5e1;border-radius:.4rem;padding:.45rem}.preview{display:grid;gap:.6rem;border-left:4px solid #f59e0b;padding-left:1rem}.separate{display:flex;gap:.7rem;align-items:end}.empty{text-align:center;padding:2rem}@media(max-width:900px){.profiles{grid-template-columns:1fr 1fr}.merge-form{grid-template-columns:1fr 1fr}}@media(max-width:600px){.identity-review>header,.case>header,.profiles,.comparison,.merge-form{display:grid;grid-template-columns:1fr}.confidence{text-align:left}.case footer,.separate{flex-wrap:wrap}.case footer button{flex:1}}
</style>
