<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { adminApi, apiErrorMessage } from '@/api/client';
import { useAdminContextStore } from '@/stores/adminContext';

type Row=Record<string,any>;
const context=useAdminContextStore();
const section=ref<'fulfillment'|'transfers'|'inventory'>('fulfillment');
const fulfillments=ref<Row[]>([]);const transfers=ref<Row[]>([]);const sessions=ref<Row[]>([]);const items=ref<Row[]>([]);const locations=ref<Row[]>([]);const orders=ref<Row[]>([]);
const error=ref('');const notice=ref('');const saving=ref(false);const search=ref('');
const transferStep=ref(1);const transferForm=ref({from_location_id:0,to_location_id:0,sellable_id:0,quantity:1,reason:'Réapprovisionnement'});
const inventoryForm=ref({stock_location_id:0,label:'Inventaire',hide_theoretical:false});
const fulfillmentForm=ref({order_id:0,stock_location_id:0,fulfillment_type:'shipping'});
const reconciliationRuns=ref<Row[]>([]);const diagnostic=ref<Row|null>(null);
const canFulfill=computed(()=>context.can('sale.fulfillment.manage'));const canTransfer=computed(()=>context.can('sale.transfers.manage'));const canCount=computed(()=>context.can('sale.inventory.count'));const canApprove=computed(()=>context.can('sale.inventory.approve'));const canRepair=computed(()=>context.can('sale.inventory.repair'));
const visibleFulfillments=computed(()=>{const q=search.value.trim().toLowerCase();return !q?fulfillments.value:fulfillments.value.filter(r=>JSON.stringify(r).toLowerCase().includes(q));});

async function load(){error.value='';try{const [fq,tr,se,stock,orderList,reconciliations]=await Promise.all([adminApi.get<{fulfillments:Row[]}>('/sale/fulfillment/queue'),adminApi.get<{transfers:Row[]}>('/sale/stock/transfers'),adminApi.get<{sessions:Row[]}>('/sale/inventory-sessions'),adminApi.get<{items:Row[];locations:Row[]}>('/sale/stock/items',{limit:200}),adminApi.get<{orders:Row[]}>('/sale/orders',{limit:200}),adminApi.get<{runs:Row[]}>('/sale/stock/reconciliation',{limit:20})]);fulfillments.value=fq.data.fulfillments||[];transfers.value=tr.data.transfers||[];sessions.value=se.data.sessions||[];items.value=stock.data.items||[];locations.value=stock.data.locations||[];orders.value=(orderList.data.orders||[]).filter(r=>['placed','confirmed'].includes(String(r.status)));reconciliationRuns.value=reconciliations.data.runs||[];if(!diagnostic.value&&reconciliationRuns.value[0])diagnostic.value=reconciliationRuns.value[0].report||null;if(!transferForm.value.from_location_id&&locations.value[0])transferForm.value.from_location_id=Number(locations.value[0].id);if(!transferForm.value.to_location_id&&locations.value[1])transferForm.value.to_location_id=Number(locations.value[1].id);if(!transferForm.value.sellable_id&&items.value[0])transferForm.value.sellable_id=Number(items.value[0].sellable_id);if(!inventoryForm.value.stock_location_id&&locations.value[0])inventoryForm.value.stock_location_id=Number(locations.value[0].id);if(!fulfillmentForm.value.stock_location_id&&locations.value[0])fulfillmentForm.value.stock_location_id=Number(locations.value[0].id);if(!fulfillmentForm.value.order_id&&orders.value[0])fulfillmentForm.value.order_id=Number(orders.value[0].id);}catch(e){error.value=apiErrorMessage(e)}}
async function createFulfillment(){if(!fulfillmentForm.value.order_id)return;saving.value=true;try{const detail=await adminApi.get<{order:Row}>(`/sale/orders/${fulfillmentForm.value.order_id}`);const allocated=new Map<number,number>();fulfillments.value.filter(f=>Number(f.order_id)===fulfillmentForm.value.order_id&&!['cancelled','returned'].includes(String(f.status))).flatMap(f=>f.lines||[]).forEach((line:Row)=>allocated.set(Number(line.order_line_id),(allocated.get(Number(line.order_line_id))||0)+Number(line.quantity)));const lines=(detail.data.order.lines||[]).map((line:Row)=>({order_line_id:Number(line.id),quantity:Math.max(0,Number(line.quantity)-Number(line.fulfilled_quantity||0)-(allocated.get(Number(line.id))||0))})).filter((line:Row)=>line.quantity>0);if(!lines.length)throw new Error('Toutes les quantités sont déjà allouées.');await adminApi.post(`/sale/orders/${fulfillmentForm.value.order_id}/fulfillments`,{stock_location_id:fulfillmentForm.value.stock_location_id,fulfillment_type:fulfillmentForm.value.fulfillment_type,lines});notice.value='Préparation créée et emplacement alloué.';fulfillmentForm.value.order_id=0;await load()}catch(e){error.value=apiErrorMessage(e)}finally{saving.value=false}}
async function saveLine(f:Row,line:Row,quantity:number){saving.value=true;try{await adminApi.patch(`/sale/fulfillments/${f.id}/lines/${line.id}`,{prepared_quantity:Math.max(0,Math.min(Number(line.quantity),quantity)),problem_code:null,problem_note:null});notice.value='Progression enregistrée.';await load()}catch(e){error.value=apiErrorMessage(e)}finally{saving.value=false}}
async function problem(f:Row,line:Row){const note=window.prompt('Décrivez le problème de préparation');if(!note)return;saving.value=true;try{await adminApi.patch(`/sale/fulfillments/${f.id}/lines/${line.id}`,{prepared_quantity:Number(line.prepared_quantity||0),problem_code:'operator_problem',problem_note:note});await load()}catch(e){error.value=apiErrorMessage(e)}finally{saving.value=false}}
async function transition(f:Row,status:string){const payload:Row={status};if(status==='shipped')payload.tracking_reference=window.prompt('Référence de suivi (optionnelle)')||'';if(status==='handed_over'){payload.pickup_code=window.prompt('Code de retrait')||'';payload.proof=window.prompt('Preuve opérateur (nom, pièce ou signature)')||''}saving.value=true;try{await adminApi.post(`/sale/fulfillments/${f.id}/transition`,payload);notice.value='Statut logistique mis à jour.';await load()}catch(e){error.value=apiErrorMessage(e)}finally{saving.value=false}}
async function createTransfer(){saving.value=true;try{await adminApi.post('/sale/stock/transfers',{from_location_id:transferForm.value.from_location_id,to_location_id:transferForm.value.to_location_id,reason:transferForm.value.reason,lines:[{sellable_id:transferForm.value.sellable_id,quantity:transferForm.value.quantity}]});notice.value='Transfert demandé.';transferStep.value=1;await load()}catch(e){error.value=apiErrorMessage(e)}finally{saving.value=false}}
async function transferAction(row:Row,action:string){saving.value=true;try{const quantities:Object=Object.fromEntries((row.lines||[]).map((l:Row)=>[String(l.id),Number(action==='ship'?l.requested_quantity:l.shipped_quantity)]));await adminApi.post(`/sale/stock/transfers/${row.id}/${action}`,action==='cancel'?{}:{quantities});await load()}catch(e){error.value=apiErrorMessage(e)}finally{saving.value=false}}
async function createInventory(){saving.value=true;try{await adminApi.post('/sale/inventory-sessions',inventoryForm.value);notice.value='Session créée, le comptage peut commencer.';await load()}catch(e){error.value=apiErrorMessage(e)}finally{saving.value=false}}
async function saveCount(session:Row,line:Row){if(line.counted_quantity===null||line.counted_quantity==='')return;try{await adminApi.patch(`/sale/inventory-sessions/${session.id}/lines/${line.id}`,{counted_quantity:Number(line.counted_quantity),discrepancy_reason:line.discrepancy_reason||null});notice.value='Comptage sauvegardé.'}catch(e){error.value=apiErrorMessage(e)}}
async function inventoryAction(row:Row,action:string){saving.value=true;try{await adminApi.post(`/sale/inventory-sessions/${row.id}/${action}`,{});await load()}catch(e){error.value=apiErrorMessage(e)}finally{saving.value=false}}
async function runDiagnostic(only:number[]=[]){saving.value=true;error.value='';try{const response=await adminApi.post<{reconciliation:Row}>('/sale/stock/reconciliation',{only_inventory_item_ids:only});diagnostic.value=response.data.reconciliation;notice.value=diagnostic.value.differences_count?'Aperçu terminé : des écarts exigent une décision.':'Reconstruction vérifiée : aucun écart.';await load()}catch(e){error.value=apiErrorMessage(e)}finally{saving.value=false}}
async function repairDiagnostic(){if(!diagnostic.value||!Number(diagnostic.value.differences_count))return;const reason=window.prompt('Motif obligatoire de la réparation après sauvegarde automatique');if(!reason||reason.trim().length<3)return;const corrections=(diagnostic.value.differences||[]).filter((f:Row)=>f.target_on_hand_quantity!==undefined&&f.target_on_hand_quantity!=='').map((f:Row)=>({inventory_item_id:Number(f.inventory_item_id),target_on_hand_quantity:Number(f.target_on_hand_quantity)}));saving.value=true;error.value='';try{const response=await adminApi.post<{reconciliation:Row}>('/sale/stock/reconciliation/repair',{reason:reason.trim(),corrections});diagnostic.value=response.data.reconciliation;notice.value=`Réparation terminée. Sauvegarde : ${diagnostic.value.backup?.path||'créée'}`;await load()}catch(e){error.value=apiErrorMessage(e)}finally{saving.value=false}}
function downloadDiagnostic(){if(!diagnostic.value)return;const blob=new Blob([JSON.stringify(diagnostic.value,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`inventory-reconciliation-${diagnostic.value.run_id||'preview'}.json`;link.click();URL.revokeObjectURL(url)}
function retryFailures(){const ids=Array.from(new Set<number>((diagnostic.value?.remaining_differences||diagnostic.value?.differences||[]).map((f:Row)=>Number(f.inventory_item_id)).filter((id:number)=>id>0)));void runDiagnostic(ids)}
onMounted(load);
</script>

<template>
 <section class="ops"><header><div><p>Vente · opérations</p><h2>Exécution logistique</h2><span>Préparer, transférer et compter avec une progression conservée.</span></div><input v-if="section==='fulfillment'" v-model="search" class="form-control" type="search" placeholder="Commande, client, code ou SKU"></header>
 <nav><button v-for="tab in ['fulfillment','transfers','inventory']" :key="tab" type="button" :class="{active:section===tab}" @click="section=tab as any">{{ tab==='fulfillment'?'Préparations':tab==='transfers'?'Transferts':'Inventaires' }}</button></nav>
 <div v-if="notice" class="alert alert-success">{{ notice }}</div><div v-if="error" class="alert alert-danger">{{ error }}</div>
 <section v-if="section==='fulfillment'" class="cards"><form v-if="canFulfill" class="panel allocation" @submit.prevent="createFulfillment"><h3>Allouer une commande</h3><label>Commande<select v-model.number="fulfillmentForm.order_id" class="form-select"><option :value="0">Choisir…</option><option v-for="o in orders" :key="o.id" :value="o.id">{{ o.order_number }} · {{ o.fulfillment_status }}</option></select></label><label>Mode<select v-model="fulfillmentForm.fulfillment_type" class="form-select"><option value="shipping">Expédition</option><option value="pickup">Retrait local</option></select></label><label>Emplacement<select v-model.number="fulfillmentForm.stock_location_id" class="form-select"><option v-for="l in locations" :key="l.id" :value="l.id">{{ l.name }}</option></select></label><button class="btn btn-primary" :disabled="!fulfillmentForm.order_id||saving">Créer la préparation</button></form><p v-if="!visibleFulfillments.length" class="empty">Aucune préparation dans la file.</p><article v-for="f in visibleFulfillments" :key="f.id" :class="['card',f.status]"><header><div><small>{{ f.fulfillment_number }} · {{ f.location_name }}</small><h3>{{ f.order_number }}</h3><span>{{ f.customer?.name || f.customer?.email || 'Client' }}</span></div><b>{{ f.status }}<small>Prochaine action : {{ f.next_action }}</small></b></header><div v-for="line in f.lines" :key="line.id" class="line"><div><strong>{{ line.product_name }}</strong><small>{{ line.variant_name || line.sku }}</small></div><span>Reste <b>{{ Number(line.quantity)-Number(line.prepared_quantity) }}</b> / {{ line.quantity }}</span><div v-if="canFulfill" class="actions"><button type="button" @click="saveLine(f,line,Number(line.prepared_quantity)-1)">−</button><button type="button" @click="saveLine(f,line,Number(line.prepared_quantity)+1)">+</button><button type="button" @click="saveLine(f,line,Number(line.quantity))">Tout</button><button type="button" class="danger" @click="problem(f,line)">Problème</button></div></div><footer v-if="canFulfill"><button v-if="f.status==='preparing'&&f.fulfillment_type==='pickup'" class="btn btn-primary" @click="transition(f,'ready_for_pickup')">Prêt au retrait</button><button v-if="f.status==='ready_for_pickup'" class="btn btn-primary" @click="transition(f,'handed_over')">Remis au client</button><button v-if="f.status==='preparing'&&f.fulfillment_type==='shipping'" class="btn btn-primary" @click="transition(f,'shipped')">Expédier</button><button v-if="f.status==='shipped'" class="btn btn-outline-primary" @click="transition(f,'delivered')">Confirmer la livraison</button></footer></article></section>
 <section v-if="section==='transfers'" class="split"><form class="panel" @submit.prevent="transferStep<6?transferStep++:createTransfer()"><h3>Nouveau transfert · étape {{ transferStep }}/6</h3><label v-if="transferStep===1">Origine<select v-model.number="transferForm.from_location_id" class="form-select"><option v-for="l in locations" :key="l.id" :value="l.id">{{ l.name }}</option></select></label><label v-if="transferStep===1">Destination<select v-model.number="transferForm.to_location_id" class="form-select"><option v-for="l in locations" :key="l.id" :value="l.id">{{ l.name }}</option></select></label><label v-if="transferStep===2">Article<select v-model.number="transferForm.sellable_id" class="form-select"><option v-for="i in items.filter(x=>Number(x.stock_location_id)===transferForm.from_location_id)" :key="i.id" :value="i.sellable_id">{{ i.product_name||i.sku }} · {{ i.available_quantity }}</option></select></label><label v-if="transferStep===2">Quantité<input v-model.number="transferForm.quantity" class="form-control" min="1" type="number"></label><label v-if="transferStep===3">Motif<input v-model="transferForm.reason" class="form-control"></label><p v-if="transferStep>3">{{ locations.find(x=>x.id===transferForm.from_location_id)?.name }} → {{ locations.find(x=>x.id===transferForm.to_location_id)?.name }} · {{ transferForm.quantity }} unité(s)</p><footer><button v-if="transferStep>1" type="button" class="btn btn-outline-secondary" @click="transferStep--">Précédent</button><button v-if="canTransfer" class="btn btn-primary">{{ transferStep<6?'Suivant':'Valider la demande' }}</button></footer></form><div class="panel"><h3>Transferts en cours</h3><article v-for="r in transfers" :key="r.id" class="list"><div><strong>{{ r.transfer_number }}</strong><small>{{ r.reason }} · {{ r.status }}</small></div><div v-if="canTransfer"><button v-if="r.status==='requested'" @click="transferAction(r,'ship')">Expédier</button><button v-if="['in_transit','partially_received','discrepancy'].includes(r.status)" @click="transferAction(r,'receive')">Réceptionner</button><button v-if="['draft','requested'].includes(r.status)" @click="transferAction(r,'cancel')">Annuler</button></div></article></div></section>
 <section v-if="section==='inventory'" class="panel reconciliation"><header><div><h3>Diagnostic de reconstruction</h3><p>Le dry-run compare cache, journal, réservations, opérations et projection Shop sans modifier le stock.</p></div><div class="actions"><button class="btn btn-outline-primary" :disabled="saving" @click="runDiagnostic()">Lancer l’aperçu</button><button v-if="diagnostic" class="btn btn-outline-secondary" @click="downloadDiagnostic">Télécharger</button><button v-if="diagnostic&&Number(diagnostic.remaining_differences_count??diagnostic.differences_count)>0" class="btn btn-outline-secondary" :disabled="saving" @click="retryFailures">Relancer les échecs</button><button v-if="canRepair&&diagnostic&&Number(diagnostic.remaining_differences_count??diagnostic.differences_count)>0" class="btn btn-danger" :disabled="saving||diagnostic.mode!=='dry_run'" @click="repairDiagnostic">Réparer après sauvegarde</button></div></header><p v-if="saving" class="alert alert-info">Analyse ou réparation en cours…</p><div v-if="diagnostic" class="reconciliation-summary"><span>Mode <b>{{ diagnostic.mode }}</b></span><span>Items <b>{{ diagnostic.items_checked }}</b></span><span>Écarts <b>{{ diagnostic.differences_count }}</b></span><span>Critiques <b>{{ diagnostic.critical_count }}</b></span><span>Restants <b>{{ diagnostic.remaining_differences_count }}</b></span><span>Shop <b>{{ diagnostic.shop_projection?.consistent?'cohérent':'à reconstruire' }}</b></span></div><article v-for="finding in diagnostic?.differences||[]" :key="finding.id" :class="['finding',finding.severity]"><header><div><strong>{{ finding.kind }} · item #{{ finding.inventory_item_id }}</strong><small>{{ finding.severity }}</small></div><span>Avant <b>{{ JSON.stringify(finding.before) }}</b> → Après <b>{{ JSON.stringify(finding.after_preview) }}</b></span></header><p>{{ finding.impact }}</p><small>Cause probable : {{ finding.probable_cause }}</small><div class="finding-actions"><a :href="finding.references?.links?.movements">Mouvements</a><a :href="finding.references?.links?.reservations">Réservations</a><label v-if="finding.kind==='physical_ledger'">Quantité physique constatée (optionnel)<input v-model.number="finding.target_on_hand_quantity" class="form-control" type="number" min="0"></label></div></article><details v-if="reconciliationRuns.length"><summary>Historique des diagnostics</summary><button v-for="run in reconciliationRuns" :key="run.id" type="button" class="history-run" @click="diagnostic=run.report">#{{ run.id }} · {{ run.mode }} · {{ run.status }} · {{ run.differences_count }} écart(s)</button></details></section>
 <section v-if="section==='inventory'" class="split"><form class="panel" @submit.prevent="createInventory"><h3>Nouvelle session</h3><label>Emplacement<select v-model.number="inventoryForm.stock_location_id" class="form-select"><option v-for="l in locations" :key="l.id" :value="l.id">{{ l.name }}</option></select></label><label>Libellé<input v-model="inventoryForm.label" class="form-control"></label><label><input v-model="inventoryForm.hide_theoretical" type="checkbox"> Masquer le stock théorique pendant le comptage</label><button v-if="canCount" class="btn btn-primary">Commencer</button></form><div class="panel"><article v-for="s in sessions" :key="s.id" class="session"><header><div><strong>{{ s.session_number }} · {{ s.location_name }}</strong><small>{{ s.status }}</small></div><div><button v-if="s.status==='counting'&&canCount" @click="inventoryAction(s,'submit')">Revoir les écarts</button><button v-if="s.status==='review'&&canApprove" @click="inventoryAction(s,'approve')">Valider</button></div></header><div v-for="line in s.lines" :key="line.id" class="count"><span>{{ line.product_name||line.sku }}</span><small v-if="line.expected_quantity!==null">Théorique {{ line.expected_quantity }}</small><input v-model.number="line.counted_quantity" type="number" min="0" placeholder="Compté" @change="saveCount(s,line)"><input v-if="line.counted_quantity!==null&&Number(line.counted_quantity)!==Number(line.expected_quantity)" v-model="line.discrepancy_reason" placeholder="Motif de l’écart" @change="saveCount(s,line)"></div></article></div></section>
 </section>
</template>

<style scoped>
.ops{display:grid;gap:1rem}.ops>header,.card>header,.session>header,.reconciliation>header,.finding>header{display:flex;justify-content:space-between;gap:1rem}.ops>header p{margin:0;color:#6366f1;font-weight:700;text-transform:uppercase;font-size:.75rem}.ops>header input{max-width:24rem}.ops nav{display:flex;gap:.4rem;border-bottom:1px solid #e2e8f0}.ops nav button{border:0;background:transparent;padding:.7rem 1rem}.ops nav .active{border-bottom:3px solid #4f46e5;color:#4338ca;font-weight:700}.cards{display:grid;gap:.8rem}.card,.panel{border:1px solid #e2e8f0;border-radius:.8rem;background:#fff;padding:1rem}.allocation{grid-template-columns:1.4fr 1fr 1.4fr auto;align-items:end}.allocation h3{grid-column:1/-1}.card.blocked{border-color:#ef4444}.card.ready_for_pickup{border-color:#16a34a}.card header b,.card header div,.line>div,.list>div,.session header>div{display:grid}.card small,.list small,.session small,.finding small{color:#64748b}.line{display:grid;grid-template-columns:2fr 1fr auto;gap:.8rem;align-items:center;padding:.7rem 0;border-top:1px solid #eef2f7}.actions{display:flex;gap:.3rem;flex-wrap:wrap}.actions button,.list button,.session button{border:1px solid #cbd5e1;border-radius:.4rem;background:#fff;padding:.35rem .55rem}.actions .danger{color:#b91c1c}.card footer,.panel footer{display:flex;justify-content:flex-end;gap:.5rem;margin-top:.7rem}.split{display:grid;grid-template-columns:minmax(18rem,1fr) 2fr;gap:1rem}.panel{display:grid;gap:.8rem;align-content:start}.panel label{display:grid;gap:.3rem}.list{display:flex;justify-content:space-between;padding:.7rem 0;border-top:1px solid #eef2f7}.session{border-bottom:1px solid #e2e8f0;padding:.8rem 0}.count{display:grid;grid-template-columns:2fr 1fr 1fr 2fr;gap:.5rem;align-items:center;padding:.35rem 0}.count input{min-width:0;padding:.35rem;border:1px solid #cbd5e1;border-radius:.35rem}.reconciliation-summary{display:grid;grid-template-columns:repeat(6,1fr);gap:.5rem}.reconciliation-summary span{display:grid;padding:.7rem;background:#f8fafc;border-radius:.5rem}.finding{padding:.8rem;border:1px solid #fed7aa;border-left:5px solid #f97316;border-radius:.5rem}.finding.critical{border-color:#fecaca;border-left-color:#dc2626;background:#fef2f2}.finding-actions{display:flex;align-items:end;gap:1rem;flex-wrap:wrap}.finding-actions label{min-width:16rem}.history-run{display:block;width:100%;text-align:left;border:0;border-top:1px solid #e2e8f0;background:#fff;padding:.5rem}.empty{text-align:center;padding:2rem}@media(max-width:800px){.split,.allocation,.reconciliation-summary{grid-template-columns:1fr}.line,.count{grid-template-columns:1fr}.ops>header,.reconciliation>header,.finding>header{display:grid}.ops>header input{max-width:none}.actions{flex-wrap:wrap}}
</style>
