<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { AdminApiError, adminApi } from '@/api/client';
import type { EditorialBlock } from '@/api/contracts';

defineOptions({ name: 'CommerceBlockDataEditor' });
type Candidate = { product_id: number; name: string; sku: string; image?: string; availability?: string; status_label?: string; channel_id?: number };
const props = defineProps<{ modelValue: EditorialBlock; siteId?: number | null; languageCode?: string }>();
const emit = defineEmits<{ 'update:modelValue': [value: EditorialBlock] }>();
const query = ref(''); const candidates = ref<Candidate[]>([]); const loading = ref(false); const previewing = ref(false); const error = ref(''); const preview = ref<Record<string, any> | null>(null);
const data = computed(() => props.modelValue.data || {}); const isGrid = computed(() => props.modelValue.type === 'product_grid'); const isCart = computed(() => props.modelValue.type === 'add_to_cart'); const mode = computed(() => String(data.value.selection_mode || 'explicit'));
function list(value: unknown): number[] { if (typeof value === 'string') { const raw = value; try { value = JSON.parse(raw); } catch { value = raw.split(','); } } return Array.isArray(value) ? [...new Set(value.map(Number).filter((id) => id > 0))] : []; }
const selectedIds = computed(() => list(data.value.product_ids)); const manualIds = computed(() => list(data.value.manual_product_ids));
function update(handle: string, value: unknown) { emit('update:modelValue', { ...props.modelValue, data: { ...data.value, [handle]: value } }); }
function patch(values: Record<string, unknown>) { emit('update:modelValue', { ...props.modelValue, data: { ...data.value, ...values } }); }
async function search() { loading.value = true; error.value = ''; try { const response = await adminApi.get<{ products: Candidate[] }>('/business/pim/storefront-blocks/candidates', { site_id: props.siteId || undefined, language_code: props.languageCode || undefined, locale: props.languageCode || undefined, q: query.value, limit: 30 }); candidates.value = response.data.products || []; } catch (reason) { error.value = reason instanceof AdminApiError ? reason.message : 'Recherche de produits impossible.'; } finally { loading.value = false; } }
function choose(candidate: Candidate) { if (isCart.value || !isGrid.value) { patch({ product_id: candidate.product_id, product_ids: [candidate.product_id], sellable_id: null }); return; } const ids = selectedIds.value; update('product_ids', ids.includes(candidate.product_id) ? ids.filter((id) => id !== candidate.product_id) : [...ids, candidate.product_id]); }
function selected(candidate: Candidate): boolean { return isCart.value || !isGrid.value ? Number(data.value.product_id || 0) === candidate.product_id : selectedIds.value.includes(candidate.product_id); }
function moveManual(index: number, direction: number) { const items = [...manualIds.value]; const target = index + direction; if (target < 0 || target >= items.length) return; [items[index], items[target]] = [items[target], items[index]]; update('manual_product_ids', items); }
function removeManual(id: number) { update('manual_product_ids', manualIds.value.filter((item) => item !== id)); }
function addManual(event: Event) { const input = event.target as HTMLInputElement; const id = Number(input.value); if (id > 0 && !manualIds.value.includes(id)) update('manual_product_ids', [...manualIds.value, id]); input.value = ''; }
function candidateName(id: number): string { return candidates.value.find((candidate) => candidate.product_id === id)?.name || `Produit #${id}`; }
async function refreshPreview() { previewing.value = true; error.value = ''; try { const response = await adminApi.post<{ block: EditorialBlock }>('/business/pim/storefront-blocks/preview', { site_id: props.siteId || undefined, language_code: props.languageCode || undefined, locale: props.languageCode || undefined, block: props.modelValue }); preview.value = response.data.block.data || {}; } catch (reason) { error.value = reason instanceof AdminApiError ? reason.message : 'Aperçu Commerce impossible. Vos critères sont conservés.'; } finally { previewing.value = false; } }
watch(() => [props.siteId, props.languageCode], () => { candidates.value = []; preview.value = null; });
</script>

<template>
  <div class="commerce-block-editor">
    <section class="native-blueprint-section">
      <h3 class="native-blueprint-section__title">Produit Commerce</h3>
      <p class="field-help">La révision conserve uniquement les références et critères. Les données affichées viennent de la projection Storefront du site, de la langue et du canal actifs.</p>
      <div v-if="isGrid" class="block-grid">
        <label class="native-field native-field--wide">Mode principal<select :value="mode" @change="update('selection_mode', ($event.target as HTMLSelectElement).value)"><option value="explicit">Produits choisis</option><option value="brand">Marque</option><option value="category">Catégorie</option><option value="group">Groupe</option><option value="attribute">Attribut public</option><option value="promotion">Promotion active</option><option value="new">Nouveautés</option><option value="popular">Popularité</option><option value="relation">Relation au produit courant</option></select></label>
        <label v-if="mode === 'brand'" class="native-field">Marque (ID ou slug)<input :value="String(data.brand || '')" @input="update('brand', ($event.target as HTMLInputElement).value)"></label>
        <label v-if="mode === 'category'" class="native-field">Catégorie (ID ou slug)<input :value="String(data.category || data.collection_id || '')" @input="update('category', ($event.target as HTMLInputElement).value)"></label>
        <label v-if="mode === 'group'" class="native-field">Groupe (ID ou code)<input :value="String(data.group || '')" @input="update('group', ($event.target as HTMLInputElement).value)"></label>
        <template v-if="mode === 'attribute'"><label class="native-field">Code de l’attribut<input :value="String(data.attribute_code || '')" @input="update('attribute_code', ($event.target as HTMLInputElement).value)"></label><label class="native-field">Valeurs séparées par des virgules<input :value="Array.isArray(data.attribute_values) ? data.attribute_values.join(', ') : String(data.attribute_values || '')" @input="update('attribute_values', ($event.target as HTMLInputElement).value.split(',').map((v) => v.trim()).filter(Boolean))"></label></template>
        <label v-if="mode === 'promotion'" class="native-field">Ordre<select :value="String(data.promotion_rule || 'percent')" @change="update('promotion_rule', ($event.target as HTMLSelectElement).value)"><option value="percent">Pourcentage de remise</option><option value="amount">Montant de remise</option></select></label>
        <template v-if="mode === 'relation'"><label class="native-field">Relation<select :value="String(data.relation_type || 'related')" @change="update('relation_type', ($event.target as HTMLSelectElement).value)"><option value="related">Produits liés</option><option value="alternative">Alternatives</option><option value="accessory">Accessoires</option><option value="upsell">Montée en gamme</option><option value="cross_sell">Vente croisée</option></select></label><label class="native-field">Produit source (optionnel)<input type="number" :value="Number(data.source_product_id || 0) || ''" @input="update('source_product_id', Number(($event.target as HTMLInputElement).value) || null)"></label></template>
        <label v-if="mode === 'popular'" class="native-field">Fenêtre de popularité (jours)<input type="number" min="1" max="365" :value="Number(data.window_days || 30)" @input="update('window_days', Number(($event.target as HTMLInputElement).value) || 30)"></label>
      </div>
      <div v-if="mode === 'explicit' || !isGrid" class="commerce-product-search">
        <label class="native-field native-field--wide">Rechercher par nom ou SKU<span class="commerce-search-line"><input v-model="query" placeholder="Nom ou SKU" @keydown.enter.prevent="search"><button type="button" :disabled="loading" @click="search">{{ loading ? 'Recherche…' : 'Rechercher' }}</button></span></label>
        <div v-if="candidates.length" class="commerce-candidates" role="list" aria-label="Produits Commerce"><button v-for="candidate in candidates" :key="candidate.product_id" type="button" class="commerce-candidate" :class="{ selected: selected(candidate) }" :aria-pressed="selected(candidate)" @click="choose(candidate)"><img v-if="candidate.image" :src="candidate.image" alt="" width="48" height="48"><span v-else class="candidate-image" aria-hidden="true">□</span><span><strong>{{ candidate.name }}</strong><small>{{ candidate.sku || 'Sans SKU' }} · {{ candidate.status_label || 'Publié' }} · canal #{{ candidate.channel_id }} · {{ candidate.availability || 'État indisponible' }}</small></span></button></div>
        <p v-else-if="!loading" class="muted">Recherchez un produit publié. Une référence devenue privée, incomplète ou absente du canal sera signalée dans l’aperçu.</p>
      </div>
    </section>

    <section v-if="isGrid" class="native-blueprint-section"><h3 class="native-blueprint-section__title">Surcharge manuelle ordonnée</h3><p class="field-help">Ces produits passent en premier sans remplacer le critère principal.</p><input type="number" min="1" placeholder="ID produit — Entrée pour ajouter" @keydown.enter.prevent="addManual"><ol class="manual-list"><li v-for="(id, index) in manualIds" :key="id"><span>{{ candidateName(id) }}</span><button type="button" :disabled="index === 0" :aria-label="`Monter ${candidateName(id)}`" @click="moveManual(index, -1)">↑</button><button type="button" :disabled="index === manualIds.length - 1" :aria-label="`Descendre ${candidateName(id)}`" @click="moveManual(index, 1)">↓</button><button type="button" @click="removeManual(id)">Retirer</button></li></ol></section>

    <section class="native-blueprint-section"><h3 class="native-blueprint-section__title">Affichage</h3>
      <div v-if="isCart" class="block-grid"><label class="native-field">Vendable précis (optionnel)<input type="number" :value="Number(data.sellable_id || 0) || ''" @input="update('sellable_id', Number(($event.target as HTMLInputElement).value) || null)"></label><label class="native-field">Quantité<input type="number" min="1" max="100" :value="Number(data.quantity || 1)" @input="update('quantity', Number(($event.target as HTMLInputElement).value) || 1)"></label><label class="native-field native-field--wide">Libellé<input :value="String(data.label || 'Ajouter au panier')" @input="update('label', ($event.target as HTMLInputElement).value)"></label></div>
      <div v-else class="block-grid"><label class="native-field">Limite<input type="number" min="1" max="100" :value="Number(data.limit || (isGrid ? 12 : 1))" @input="update('limit', Number(($event.target as HTMLInputElement).value) || 1)"></label><label class="native-field">Colonnes<input type="number" min="1" max="6" :value="Number(data.columns || (isGrid ? 3 : 1))" @input="update('columns', Number(($event.target as HTMLInputElement).value) || 1)"></label><label class="checkline checkline--modal native-field"><input type="checkbox" :checked="data.show_price !== false" @change="update('show_price', ($event.target as HTMLInputElement).checked)"> Prix</label><label class="checkline checkline--modal native-field"><input type="checkbox" :checked="data.show_promotion !== false" @change="update('show_promotion', ($event.target as HTMLInputElement).checked)"> Promotion</label><label class="checkline checkline--modal native-field"><input type="checkbox" :checked="data.show_availability !== false" @change="update('show_availability', ($event.target as HTMLInputElement).checked)"> Disponibilité</label><label class="checkline checkline--modal native-field"><input type="checkbox" :checked="data.show_cta !== false" @change="update('show_cta', ($event.target as HTMLInputElement).checked)"> Action</label><label v-if="isGrid" class="checkline checkline--modal native-field"><input type="checkbox" :checked="Boolean(data.pagination)" @change="update('pagination', ($event.target as HTMLInputElement).checked)"> Pagination</label><label class="native-field native-field--wide">Message vide<input :value="String(data.empty_message || 'Aucun produit à afficher.')" @input="update('empty_message', ($event.target as HTMLInputElement).value)"></label></div>
    </section>

    <section class="native-blueprint-section commerce-preview"><div class="nested-panel__header"><h3 class="native-blueprint-section__title">Contrôle de la sélection</h3><button type="button" :disabled="previewing" @click="refreshPreview">{{ previewing ? 'Calcul…' : 'Actualiser l’aperçu' }}</button></div><p v-if="error" role="alert" class="notice notice--error">{{ error }}</p><template v-if="preview"><p><strong>{{ Number(preview.selection?.total ?? preview.selection?.count ?? (preview.product ? 1 : 0)) }}</strong> résultat(s) dans le contexte actif.</p><p v-if="preview.selection?.missing_product_ids?.length" role="status" class="notice notice--warning">Références dépubliées, incomplètes ou absentes du canal : {{ preview.selection.missing_product_ids.join(', ') }}.</p><p v-if="preview.requires_variant_choice" role="status" class="notice notice--info">Plusieurs variantes sont possibles : le visiteur sera dirigé vers la fiche produit.</p><div class="preview-items"><a v-for="item in preview.items || (preview.product ? [preview.product] : [])" :key="item.product_id" :href="`/admin/app/business/products?product_id=${item.product_id}`" target="_blank" rel="noopener"><img v-if="item.media?.[0]?.url" :src="item.media[0].url" alt="" width="56" height="56"><span><strong>{{ item.name }}</strong><small>{{ item.sku || `#${item.product_id}` }}</small></span></a></div></template><p v-else class="muted">Le contrôle utilise le même DTO que le rendu public. L’aperçu de page Studio permet le contrôle desktop et mobile.</p></section>
  </div>
</template>

<style scoped>
.commerce-search-line{display:flex;gap:.5rem}.commerce-search-line input{flex:1}.commerce-candidates,.preview-items{display:grid;gap:.5rem;grid-template-columns:repeat(auto-fit,minmax(14rem,1fr));margin-top:.75rem}.commerce-candidate,.preview-items a{align-items:center;background:var(--surface,#fff);border:1px solid var(--border,#ccd3dc);border-radius:.5rem;color:inherit;display:flex;gap:.65rem;padding:.55rem;text-align:left;text-decoration:none}.commerce-candidate.selected{border-color:var(--primary,#1463df);box-shadow:0 0 0 2px color-mix(in srgb,var(--primary,#1463df) 20%,transparent)}.commerce-candidate img,.candidate-image,.preview-items img{border-radius:.35rem;height:48px;object-fit:cover;width:48px}.commerce-candidate span,.preview-items span{display:grid}.commerce-candidate small,.preview-items small{color:var(--muted,#667085)}.manual-list{display:grid;gap:.35rem;padding-left:1.4rem}.manual-list li{align-items:center;display:flex;gap:.35rem}.manual-list li span{flex:1}@media(max-width:640px){.commerce-search-line{align-items:stretch;flex-direction:column}.commerce-candidates,.preview-items{grid-template-columns:1fr}}
</style>
