import { test, expect, type Page } from '@playwright/test';

const baseUrl=process.env.E2E_BASE_URL;const email=process.env.E2E_ADMIN_EMAIL;const password=process.env.E2E_ADMIN_PASSWORD;const enabled=Boolean(baseUrl&&email&&password);
function cmsPath(path:string){if(!baseUrl)return path;const prefix=new URL(baseUrl).pathname.replace(/\/+$/,'');return `${prefix}/${path.replace(/^\/+/, '')}`.replace(/\/{2,}/g,'/')}
async function signIn(page:Page){await page.goto(cmsPath('/admin/login'));await page.getByLabel('Email').fill(email!);await page.getByRole('button',{name:/continuer/i}).click();await page.locator('input[name="password"]').fill(password!);await page.getByRole('button',{name:/se connecter/i}).click();await expect(page).toHaveURL(/\/admin\/app(?:\/|$)/)}

const reviewCase={id:7,order_id:77,order_number:'WEB-0077',status:'pending',confidence_score:95,confidence_level:'high',candidate_iam_user_id:12,candidate_crm_contact_id:20,signals:[{rule:'verified_iam_email',weight:65,explanation:'Compte avec e-mail vérifié concordant'},{rule:'verified_crm_email',weight:30,explanation:'E-mail CRM vérifié concordant'}],divergences:[{field:'last_name',explanation:'Valeurs divergentes : décision humaine requise'}],profiles:{transactional_customer:{fields:{email:'client@example.test',first_name:'Anne',last_name:'Commande'}},iam_account:{fields:{email:'client@example.test',first_name:'Anne',last_name:'Compte'}},crm_contact:{fields:{email:'client@example.test',first_name:'Anne',last_name:'CRM'}},organization:{fields:{name:'Client individuel'}}},provenance:{email:[{source:'checkout'},{source:'account'}],last_name:[{source:'checkout'},{source:'import'}]},orders:[{id:77,order_number:'WEB-0077',grand_total_minor:9900,currency:'CHF'}],activities:[{id:2,summary:'Commande passée WEB-0077',status:'placed'}]};

test.describe('M7.1 revue conservatrice des identités',()=>{test.skip(!enabled,'Dedicated E2E admin environment is required');test('explains evidence, links explicitly and previews every merge conflict',async({page})=>{await signIn(page);const decisionBodies:any[]=[];let mergeBody:any=null;await page.route('**/admin/api/sale/**',async route=>{const request=route.request();const path=new URL(request.url()).pathname;let data:any={};if(path.endsWith('/customer-identities/review'))data={cases:[reviewCase]};else if(path.endsWith('/customer-identities/7/decision')){decisionBodies.push(request.postDataJSON());data={case:{...reviewCase,status:'linked'}}}else if(path.endsWith('/customer-accounts/merge-preview'))data={preview:{orders_affected:2,snapshot_policy:'immutable',conflicts:['last_name','email'],fields:{last_name:{source:'Commande',target:'Compte',allowed_choices:['source','target']},email:{source:'old@example.test',target:'client@example.test',allowed_choices:['target']}}}};else if(path.endsWith('/customer-accounts/merge')){mergeBody=request.postDataJSON();data={merge:{id:9,status:'applied'}}}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data})})});
await page.goto(cmsPath('/admin/app/business/relations/advanced/profiles'));await expect(page.getByRole('heading',{name:'Rapprochement de profils'})).toBeVisible();await expect(page.getByText('Commande WEB-0077')).toBeVisible();await expect(page.getByText('95 %')).toBeVisible();await expect(page.getByText('Compte avec e-mail vérifié concordant')).toBeVisible();await expect(page.getByText('Valeurs divergentes : décision humaine requise')).toBeVisible();await page.getByText('Commandes et activités concernées').click();await expect(page.getByText('Commande passée WEB-0077')).toBeVisible();page.once('dialog',dialog=>dialog.accept('Preuves vérifiées par le service client'));await page.getByRole('button',{name:'Lier',exact:true}).click();await expect.poll(()=>decisionBodies.length).toBe(1);expect(decisionBodies[0]).toMatchObject({data:{action:'link',reason:'Preuves vérifiées par le service client'}});
page.once('dialog',dialog=>dialog.accept('Informations insuffisantes, nouvelle vérification nécessaire'));await page.getByRole('button',{name:'Reporter',exact:true}).click();await expect.poll(()=>decisionBodies.length).toBe(2);expect(decisionBodies[1]).toMatchObject({data:{action:'postpone',reason:'Informations insuffisantes, nouvelle vérification nécessaire'}});
await page.getByLabel('Compte source').fill('11');await page.getByLabel('Compte cible').fill('12');await page.getByRole('button',{name:'Prévisualiser'}).click();await expect(page.getByText('snapshots immuables')).toBeVisible();await expect(page.getByText('Source : old@example.test · Cible : client@example.test')).toBeVisible();await page.getByRole('button',{name:'Fusionner avec ces décisions'}).click();expect(mergeBody.data.field_decisions).toMatchObject({email:'target'});await page.setViewportSize({width:390,height:844});await expect(page.getByRole('heading',{name:'Rapprochement de profils'})).toBeVisible()})});
