import { test, expect, type Page } from '@playwright/test';

const baseUrl=process.env.E2E_BASE_URL; const email=process.env.E2E_ADMIN_EMAIL; const password=process.env.E2E_ADMIN_PASSWORD; const enabled=Boolean(baseUrl&&email&&password);
const cmsPath=(path:string):string=>{if(!baseUrl)return path;const prefix=new URL(baseUrl).pathname.replace(/\/+$/,'');return`${prefix}/${path.replace(/^\/+/, '')}`.replace(/\/{2,}/g,'/');};
async function signIn(page:Page){await page.goto(cmsPath('/admin/login'));await page.getByLabel('Email').fill(email!);await page.getByRole('button',{name:/continuer/i}).click();await page.locator('input[name="password"]').fill(password!);await page.getByRole('button',{name:/se connecter/i}).click();const response=await page.request.get(cmsPath('/admin/api/context'));expect(response.ok(),await response.text()).toBeTruthy();return(await response.json()).data;}
const headers=(csrf:string)=>({'Content-Type':'application/json','X-Contract-Version':'admin-api-v1','X-CSRF-Token':csrf});

test.describe('43 blocs Commerce dans Studio',()=>{
  test.skip(!enabled,'Dedicated E2E environment and administrator credentials are required');
  test('publishes a projection-backed marketing page and completes its guest purchase',async({page})=>{
    test.setTimeout(120_000);
    const context=await signIn(page);const siteId=Number(context.site.id);const locale=String(context.current_content_language_code||context.site.default_language_code||'fr');
    const rebuild=await page.request.post(cmsPath('/admin/api/business/pim/storefront-projections/rebuild'),{headers:headers(context.csrf_token),data:{data:{locale}}});expect(rebuild.ok(),await rebuild.text()).toBeTruthy();
    const productsResponse=await page.request.get(cmsPath(`/api/v1/storefront/products?lang=${locale}&limit=100`));expect(productsResponse.ok(),await productsResponse.text()).toBeTruthy();const products=(await productsResponse.json()).data.items as any[];const product=products.find((item)=>item.type==='physical'&&item.cta?.sellable_id);expect(product?.product_id).toBeGreaterThan(0);
    const suffix=`commerce-43-${Date.now()}`;const block={id:'commerce-grid-e2e',type:'product_grid',enabled:true,editorial_status:'published',data:{selection_mode:'explicit',product_ids:[product.product_id],limit:4,columns:3,show_price:true,show_promotion:true,show_availability:true,show_cta:true,empty_state:'message',empty_message:'Aucun produit disponible.'}};
    const previewResponse=await page.request.post(cmsPath('/admin/api/business/pim/storefront-blocks/preview'),{headers:headers(context.csrf_token),data:{data:{site_id:siteId,language_code:locale,locale,block}}});expect(previewResponse.ok(),await previewResponse.text()).toBeTruthy();const preview=(await previewResponse.json()).data.block;expect(preview.data.items[0].product_id).toBe(product.product_id);
    const draftResponse=await page.request.post(cmsPath('/admin/api/entries'),{headers:headers(context.csrf_token),data:{data:{site_id:siteId,language_code:locale,content_type_key:'page',entry_key:suffix,title:'Sélection Commerce E2E',slug:suffix,meta_title:'Sélection Commerce E2E',meta_description:'Achat depuis une page marketing',meta_robots:'noindex,follow',fields:{},taxonomy_terms:{},blocks:[block],change_notes:'Point 43 E2E'}}});expect(draftResponse.ok(),await draftResponse.text()).toBeTruthy();const draft=(await draftResponse.json()).data;
    const publishResponse=await page.request.post(cmsPath(`/admin/api/entries/${draft.entry_id}/publish`),{headers:headers(context.csrf_token),data:{data:{site_id:siteId,language_code:locale,revision_id:draft.revision_id,expected_working_revision_id:draft.revision_id}}});expect(publishResponse.ok(),await publishResponse.text()).toBeTruthy();
    const headlessResponse=await page.request.get(cmsPath(`/api/v1/content-by-path?path=${encodeURIComponent('/'+suffix)}&lang=${locale}`));expect(headlessResponse.ok(),await headlessResponse.text()).toBeTruthy();const headless=(await headlessResponse.json()).data;expect(headless.blocks[0].data.items[0].product_id).toBe(product.product_id);expect(headless.blocks[0].data.items[0].price).toEqual(preview.data.items[0].price);
    const exportResponse=await page.request.post(cmsPath('/admin/api/imports-exports/static/actions/page'),{headers:headers(context.csrf_token),data:{data:{site_id:siteId,language_code:locale,route:`/${suffix}`}}});expect(exportResponse.ok(),await exportResponse.text()).toBeTruthy();const exported=(await exportResponse.json()).data;expect(['succeeded','partial']).toContain(exported.status);expect(exported.report.routes_exported.some((route:any)=>route.path===`/${suffix}`)).toBeTruthy();
    const restoreResponse=await page.request.post(cmsPath(`/admin/api/entries/${draft.entry_id}/revisions/${draft.revision_id}/restore`),{headers:headers(context.csrf_token),data:{data:{site_id:siteId,language_code:locale}}});expect(restoreResponse.ok(),await restoreResponse.text()).toBeTruthy();const restored=(await restoreResponse.json()).data;expect(restored.restored_from_revision_id).toBe(draft.revision_id);const restoredRevisionId=Number(restored.working_revision.id);const republish=await page.request.post(cmsPath(`/admin/api/entries/${draft.entry_id}/publish`),{headers:headers(context.csrf_token),data:{data:{site_id:siteId,language_code:locale,revision_id:restoredRevisionId,expected_working_revision_id:restoredRevisionId}}});expect(republish.ok(),await republish.text()).toBeTruthy();
    await page.setViewportSize({width:390,height:844});await page.goto(cmsPath(`/${suffix}?lang=${locale}`));await expect(page.locator(`[data-product-id="${product.product_id}"]`)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);
    const add=page.locator(`[data-storefront-add-to-cart][data-sellable-id="${product.cta.sellable_id}"]`);await add.focus();await expect(add).toBeFocused();await add.press('Enter');await expect(page.locator('[data-cart-count]')).toHaveText('1');await page.locator('[data-cart-checkout]').click();
    await expect(page.getByRole('heading',{name:'Commande invitée'})).toBeVisible();await page.getByLabel('Prénom').fill('Claire');await page.getByLabel('Nom',{exact:true}).fill('Commerce');await page.getByLabel('E-mail').fill(`commerce-43-${Date.now()}@example.test`);await page.getByLabel('Adresse',{exact:true}).fill('Rue du Test 43');await page.getByLabel('Code postal').fill('1000');await page.getByLabel('Ville').fill('Lausanne');await page.locator('select[name="shipping_method"]').selectOption('standard');await page.getByLabel('J’accepte les conditions générales de vente').check();await page.getByRole('button',{name:'Commander'}).click();await expect(page.locator('[data-checkout-summary]')).toContainText('Commande SALE-');
  });
});
