#!/usr/bin/env python3
"""Génère des types TypeScript légers depuis l'OpenAPI public headless v1.

Le script lit uniquement `components.schemas` dans `docs/public-api/openapi.v1.json`
et produit un fichier déterministe, sans dépendance externe ni dépendance runtime SDK.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

ROOT = next(parent for parent in Path(__file__).resolve().parents if (parent / "tools" / "cms.py").is_file())
OPENAPI = ROOT / "docs" / "public-api" / "openapi.v1.json"
OUTPUT = ROOT / "packages" / "amcms-client" / "src" / "generated" / "openapi-types.ts"

HEADER = """// -----------------------------------------------------------------------------\n// <auto-generated>\n// Généré par tools/python/generators/c44_generate_sdk_types_from_openapi.py.\n// Source: docs/public-api/openapi.v1.json -> components.schemas.\n// Ne pas modifier manuellement : relancer le script de génération.\n// -----------------------------------------------------------------------------\n\n"""


def load_openapi(path: Path = OPENAPI) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def pascal_identifier(value: str) -> str:
    parts = re.split(r"[^0-9A-Za-z]+", value)
    name = "".join(part[:1].upper() + part[1:] for part in parts if part)
    if not name:
        return "Schema"
    if name[0].isdigit():
        name = "Schema" + name
    return name


def schema_type_name(schema_name: str) -> str:
    return "OpenApi" + pascal_identifier(schema_name)


def ts_string_literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def ts_property_name(name: str) -> str:
    if re.match(r"^[A-Za-z_$][0-9A-Za-z_$]*$", name):
        return name
    return ts_string_literal(name)


def ref_to_type(ref: str) -> str:
    prefix = "#/components/schemas/"
    if ref.startswith(prefix):
        return schema_type_name(ref[len(prefix) :])
    return "unknown"


def type_from_schema(schema: dict[str, Any] | bool | None, indent: int = 0) -> str:
    if schema is True:
        return "unknown"
    if schema is False or schema is None:
        return "never"
    if not isinstance(schema, dict):
        return "unknown"

    if "$ref" in schema:
        return ref_to_type(str(schema["$ref"]))

    for union_key in ("oneOf", "anyOf"):
        values = schema.get(union_key)
        if isinstance(values, list) and values:
            return join_union(type_from_schema(item, indent) for item in values)

    all_of = schema.get("allOf")
    if isinstance(all_of, list) and all_of:
        return join_intersection(type_from_schema(item, indent) for item in all_of)

    if "enum" in schema and isinstance(schema["enum"], list):
        return join_union(ts_string_literal(value) for value in schema["enum"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return join_union(type_from_schema({**schema, "type": item}, indent) for item in schema_type)

    if schema_type == "string":
        return "string"
    if schema_type == "integer" or schema_type == "number":
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        item_type = type_from_schema(schema.get("items", {}), indent)
        return f"Array<{item_type}>"
    if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
        return object_type_from_schema(schema, indent)

    return "unknown"


def object_type_from_schema(schema: dict[str, Any], indent: int = 0) -> str:
    properties = schema.get("properties") if isinstance(schema.get("properties"), dict) else {}
    additional = schema.get("additionalProperties", False)

    if not properties:
        if isinstance(additional, dict):
            return f"Record<string, {type_from_schema(additional, indent)}>"
        if additional is True:
            return "Record<string, unknown>"
        return "Record<string, never>"

    required = set(schema.get("required", [])) if isinstance(schema.get("required"), list) else set()
    spaces = " " * indent
    child_spaces = " " * (indent + 2)
    lines = ["{"]
    for name in sorted(properties):
        optional = "" if name in required else "?"
        value = type_from_schema(properties[name], indent + 2)
        lines.append(f"{child_spaces}{ts_property_name(name)}{optional}: {value};")
    if isinstance(additional, dict):
        lines.append(f"{child_spaces}[key: string]: {type_from_schema(additional, indent + 2)};")
    elif additional is True:
        lines.append(f"{child_spaces}[key: string]: unknown;")
    lines.append(f"{spaces}}}")
    return "\n".join(lines)


def join_union(values: Any) -> str:
    unique = sorted({value for value in values if value})
    if not unique:
        return "unknown"
    if len(unique) == 1:
        return unique[0]
    return " | ".join(unique)


def join_intersection(values: Any) -> str:
    unique = [value for value in values if value]
    if not unique:
        return "unknown"
    if len(unique) == 1:
        return unique[0]
    return " & ".join(unique)


def render_top_level_schema(schema_name: str, schema: dict[str, Any]) -> str:
    type_name = schema_type_name(schema_name)
    if isinstance(schema, dict) and (schema.get("type") == "object" or "properties" in schema):
        body = object_type_from_schema(schema, 0)
        if body.startswith("{"):
            return f"export interface {type_name} {body}\n"
    return f"export type {type_name} = {type_from_schema(schema, 0)};\n"


def generate_types(openapi_path: Path = OPENAPI, output_path: Path = OUTPUT) -> str:
    openapi = load_openapi(openapi_path)
    schemas = openapi.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict) or not schemas:
        raise ValueError("Aucun components.schemas trouvé dans l'OpenAPI public.")

    chunks = [HEADER]
    for schema_name in sorted(schemas):
        chunks.append(render_top_level_schema(schema_name, schemas[schema_name]))
        chunks.append("\n")

    content = "".join(chunks).rstrip() + "\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8", newline="\n")
    return content


def main() -> int:
    generate_types()
    print("OK: types TypeScript SDK générés depuis OpenAPI")
    print(f"Source: {OPENAPI.relative_to(ROOT)}")
    print(f"Sortie: {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
